### ISSUE TITLE
NavigationDrawer -> NavigationController -> PageTabBarController sample.

### ISSUE THREAD

**Issue by daniel-jonathan** [CosmicMind/Samples#1]

**Comment by daniel-jonathan** [comment]
This is a followup to an original issue on Material https://github.com/CosmicMind/Material/issues/561

**Comment by peersocialdeal** [comment]
http://sup.urb.li/syvj issue for the backbutton

It's behind the text

**Comment by daniel-jonathan** [comment]
Can you send me a sample, because that is strange. Aside from the example, I am posting an example later today. 

Send it to support@cosmicmind.io

**Comment by daniel-jonathan** [comment]
Have you had a chance to look at this example ? [NavigationDrawerController](https://github.com/CosmicMind/Samples/tree/development/Material/Programmatic/NavigationDrawerController)

**Comment by daniel-jonathan** [comment]
I posted an example of the PageTabBarController within the ToolbarController in this sample project, [CardTableView](https://github.com/CosmicMind/Samples/tree/master/Graph/CardTableView).
