### ISSUE TITLE
Textfield UI issue for RTL language

### ISSUE THREAD

**Issue by SandeepCBL** [CosmicMind/Samples#100]
I'm using Texfield. When I change language to Arabic then UI of textfield gets spoiled.
I am changing language by reloading storyboard. But also if I set device language to Arabic this issue appears. I'm attaching images.
Thanks

![screen shot 2017-11-20 at 4 38 05 pm](https://user-images.githubusercontent.com/33346121/33015700-be5c3168-ce11-11e7-862d-52e1b636696e.png)
![screen shot 2017-11-20 at 4 38 36 pm](https://user-images.githubusercontent.com/33346121/33015701-be9d0b84-ce11-11e7-968a-48ce8b7551ea.png)

**Comment by daniel-jonathan** [comment]
Yes, not all components in Material support `RTL` correctly. There is a feature request for this here https://github.com/CosmicMind/Material/issues/575. Please follow that feature request for a fix. Thank you!
