### ISSUE TITLE
Application setup: NavigationDrawer -> TabsController -> ToolbarController -> SearchBarController

### ISSUE THREAD

**Issue by daniel-jonathan** [CosmicMind/Samples#101]
@donghd Your question: 

I would like to make iOS somehow same as my Android app, when click Search button of Tool bar, it does not navigate to other screen, it still on that screen with current data, but tool bar's UI need to display Search box by relacing Toolbar's title (for ex), and work like as Search sample' Search bar functionality. So I still want TabBar be visible ... , incase each Tab Bar's data has many rows, it will be quite useful to filter data in each Tab Bar.
Thanks,

**Comment by donghd** [comment]
@danieldahan : Sorry, do you have any update about this sample?
Or any tips are welcome!

**Comment by Dmurph24** [comment]
+1

**Comment by adamdahan** [comment]
@danieldahan Let me know if I can help out with this one.
