### ISSUE TITLE
TextView does not compile

### ISSUE THREAD

**Issue by nCr78** [CosmicMind/Samples#106]
Hello! I tried running the TextView workspace after installing the pods etc. It has about 15 compiler errors. Is the textview sample deprecated? I also tried implementing it in my project but it doesn't seem to have the same features that the TextField does. Should I also open a ticket in the Material project?

**Comment by daniel-jonathan** [comment]
I will take a look into this today. There is a PR to update the TextView to behave like the TextField. That said, I will make sure the project works first. Thank you for sharing this issue.

**Comment by OrkhanAlikhanov** [comment]
The `TextView` sample successfully gets compiled and it's working. Also, there is a new `Editor` component having the `TextField-like` features (animated placeholder, details label)

**Comment by daniel-jonathan** [comment]
Thank you!
