### ISSUE TITLE
No such module 'Material'

### ISSUE THREAD

**Issue by sandeepan512** [CosmicMind/Samples#113]
No such module 'Material'

**Comment by forsan** [comment]
Same here

**Comment by daniel-jonathan** [comment]
Hey! Please elaborate on the actual issue and when you are ready, reopen this. Thank you!

**Comment by SeRG1k17** [comment]
@sandeepan512, @forsan 
After script, you need to open the Xxx.xcworkspace, for example Textfield.xcworkspace.
And **NOT** Samples.xcworkspace

**Comment by daniel-jonathan** [comment]
This should now be fixed in the latest sample update. Thank you!

**Comment by SeRG1k17** [comment]
@danieldahan Yesterday, I check it on the latest version.

**Comment by daniel-jonathan** [comment]
@SeRG1k17 which project?
