### ISSUE TITLE
Sample projects are not working

### ISSUE THREAD

**Issue by ajay2c9** [CosmicMind/Samples#115]
When sample projects are running in Xcode it is not running and showing errors.

**Comment by daniel-jonathan** [comment]
May you please elaborate? Which sample should I try and how did you install the frameworks? Thank you!

**Comment by chunta** [comment]
Projects/Programmatic/Animations/Animations/ViewController.swift:32:8: No such module 'Material'

**Comment by daniel-jonathan** [comment]
@chunta Please pull the latest, it was updated not long ago. Thank you!
