### ISSUE TITLE
No  Alert View Controller Component?

### ISSUE THREAD

**Issue by muzoman** [CosmicMind/Samples#118]
Seems conspicuous by it's absence? 

What do folks typically do when creating Apps built to Material guidelines for Alerts? Just use Apples UIAlertController? Can't believe they do as it's not customisable...

**Comment by daniel-jonathan** [comment]
Sorry, I didn't see this issue until now. We have Dialogs coming out, courtesy of @OrkhanAlikhanov. We will be grooming it and adding in default Dialogs. This is internally noted. Thank you!
