### ISSUE TITLE
How to use NavigationDrawer whit native UITabbarController?

### ISSUE THREAD

**Issue by indiefr** [CosmicMind/Samples#119]
Actually i has a  UITabBarController whit 3 Tabs, and works perfectly but i need a menu drawer left and right and this library is perfect for me, but, when i include all code of example in my project lost connection whit storyboard. My RootController is my Last Main Controller, class whit the native tabs.

Please Helpme

**Comment by OrkhanAlikhanov** [comment]
Take a look at [NavigationDrawerController sample for Storyboards](https://github.com/CosmicMind/Samples/blob/master/Projects/Storyboards/NavigationDrawerController), you need to make your `UITabBarController` root of the `NavigationDrawerController`. To do that, remove `Main storyboard file` entry from `Info.plist` and define initial hierarchy in `AppDelegate.swift`. You can still use Storyboards but you need to instantiate your `UITabBarController` from your Storyboards with an identifier to set it as the root of `NavigationDrawerController`. See [AppDelegate.swift](https://github.com/CosmicMind/Samples/blob/master/Projects/Storyboards/NavigationDrawerController/NavigationDrawerController/AppDelegate.swift) in the the sample.

**Comment by indiefr** [comment]
Really thank you!, is work perfectly whit this example.
