### ISSUE TITLE
How to open ViewControler from left or right drawer?

### ISSUE THREAD

**Issue by indiefr** [CosmicMind/Samples#120]
I try open a viewcontroller from tableview row inside to my left controller but this no open controller in my app. Used the native pushcontroller and thesamples when transition, but this no efect.
My Main controller or Root controller is whit tabbarcontroller native and i dont used the navigationcontroller.

**Comment by daniel-jonathan** [comment]
Hi @indiefr, 

We can help you at [Material Gitter](https://gitter.im/CosmicMind/Material). This isn't an actual issue, but some guidance is needed. Thank you!

**Comment by indiefr** [comment]
Well i has a solution, in my case i used NotificationCenter to open this controllers.

**Comment by daniel-jonathan** [comment]
@indiefr that's one way of doing it.

**Comment by indiefr** [comment]
Yes, and works prefectly.

**Comment by daniel-jonathan** [comment]
Awesome! All that matters is that it works, you understand it, and can maintain it.
