### ISSUE TITLE
In CheckButton Unable to change the background color

### ISSUE THREAD

**Issue by MuhammadNayabButt** [CosmicMind/Samples#121]
I have configured CheckButton in my project. But I am unable to change its background color. I have gone through the code but I found no way to change it
<img width="393" alt="screen shot 2018-08-29 at 4 26 30 pm" src="https://user-images.githubusercontent.com/7734981/44790632-387fd000-abb9-11e8-8f0a-fb5f4e1fd847.png">
s

**Comment by OrkhanAlikhanov** [comment]
Hey! Did you try `checkButton.layer.backgroundColor = UIColor.red.cgColor`?

**Comment by MuhammadNayabButt** [comment]
@OrkhanAlikhanov will try tomorrow and let you know.

**Comment by OrkhanAlikhanov** [comment]
Thank you! No rush :)

**Comment by MuhammadNayabButt** [comment]
No success.
Here is the checked and unchecked button screenshots
<img width="339" alt="checked" src="https://user-images.githubusercontent.com/7734981/44831109-7f63d900-ac3e-11e8-856c-5c00843380e7.png">
<img width="321" alt="unchecked" src="https://user-images.githubusercontent.com/7734981/44831112-7ffc6f80-ac3e-11e8-9ac8-585c1023e0ae.png">

**Comment by MuhammadNayabButt** [comment]
With little deep digging I came to know that its in "CheckBoxLayer" class which is inside CheckButton.swift
Here we have a variable "selectedColor" and "normalColor" I find no way of changing this "selectedC olor" attribute. This is my investigation and I might be out of track but at-least this is what it appears to me

`
override func prepareForFirstAnimation() {
borderLayer.borderColor = (isEnabled ? (isSelected ? selectedColor : normalColor) disabledColor).cgColor
if isSelected {
borderLayer.borderWidth = borderLayerNormalBorderWidth
} else {
 borderLayer.backgroundColor = (isEnabled ? normalColor : disabledColor).cgColor
checkMarkLeftLayer.strokeEnd = 1
 checkMarkRightLayer.strokeEnd = 1
}
 checkMarkLayer.transform = .identity
 }
`

**Comment by OrkhanAlikhanov** [comment]
Ah, by `backgroundColor` you mean `selectedColor`? You should use `setIconColor` for the checkbox itself.
```swift
let checkButton = CheckButton()
checkButton.title = "Check button"
checkButton.backgroundColor = .gray
checkButton.setIconColor(.green, for: .selected)
checkButton.setIconColor(.blue, for: .normal)
checkButton.checkmarkColor = .yellow
```

Here is the ugly result:
![](https://user-images.githubusercontent.com/15037839/44849943-c8cb1d00-ac6c-11e8-94f1-39188bae5c41.gif)

**Comment by MuhammadNayabButt** [comment]
@OrkhanAlikhanov 
Thanks man it is working

**Comment by svachmic** [comment]
@OrkhanAlikhanov I just came across this thread while having an even uglier result:

<img width="119" alt="screen shot 2018-09-03 at 18 01 20" src="https://user-images.githubusercontent.com/1448888/44995486-7b6bea00-afa3-11e8-923e-d463fe5ba9f8.png">

When selected, there is a blue border that wraps around the text. I tried endless combinations how to remove it with no luck. I'm using the same snippet you posted but the CheckBox does this...

**Comment by svachmic** [comment]
So in fact for any future references - when CheckBox is initialized via Storyboard, it's important to set `Tint` in the inspector to `Clear Color`. Solves the problem.

**Comment by daniel-jonathan** [comment]
@svachmic That is a great point. Thank you. 
@OrkhanAlikhanov Let's consider adding this the core configuration of this component.

**Comment by OrkhanAlikhanov** [comment]
@svachmic We are using `isSelected` property of the `UIButton` when the `CheckButton` is checked. That blue rounded box around the text is default look of system `UIButton` when it's selected. You should've changed type of button from `System` to `Custom` from Attributes inspector. 
![image](https://user-images.githubusercontent.com/15037839/45390795-938dda00-b631-11e8-9fe8-8f973524b949.png)
