### ISSUE TITLE
Type 'MotionTransitionAnimationType' has no member 'fadeSlide'

### ISSUE THREAD

**Issue by jbarros35** [CosmicMind/Samples#124]
I checked out the NavigationController sample
Ran pod install.
It won't compile
Type 'MotionTransitionAnimationType' has no member 'fadeSlide'

Xcode 10
Swift 4

**Comment by OrkhanAlikhanov** [comment]
Thank you for reporting. You can remove that line and continue. We'll update samples once we make a solid release.
