### ISSUE TITLE
NavigationController has no shadow or elevation

### ISSUE THREAD

**Issue by sambo-visal** [CosmicMind/Samples#125]
I am using my class as NavigationController which has navigationItem.title and navigationItem.leftViews or navigationItem.rightViews. But navigationController seems like no shadow or elevation. 

If i set background color of navigationController to white and if my view backgroundColor also white too then i will not able to see anything just title of navigationController only....

**Comment by OrkhanAlikhanov** [comment]
Try to set shadow on navigation bar of navigation controller.

```swift
class AppNavigationController: NavigationController {
  override func prepare() {
    super.prepare()
    guard let v = navigationBar as? NavigationBar else {
      return
    }
    
    v.depthPreset = .depth5
  }
}
```

**Comment by daniel-jonathan** [comment]
@OrkhanAlikhanov thank you, that is correct. I will close this, and @SamboVisal if you have any further questions, please reopen or create a new issue.

**Comment by sambo-visal** [comment]
Thank you and it works for me.. I will ask future questions soon.....
