### ISSUE TITLE
Using NavigationController in storyboard

### ISSUE THREAD

**Issue by sambo-visal** [CosmicMind/Samples#126]
Hi I really fascinated with this library. I just asked a question previously and it solved me perfectly.

Now i am coming up with another issue is that, when i created a viewController and then i embed it with navigationController which `Editor -> Embed In -> Navigation Controller` and then i inherited with AppNavigationController class in order to get NavigationController as material design view.

But unfortunately for me i don't think that it works for me.
This is how my [storyboard](https://ibb.co/g5fDEf) looks like 

This is when i run the app and then i don't think that is working for me ;( [Output](https://ibb.co/erj6Zf)

This is my AppNavigationController custom class

`class AppNavigationController: NavigationController {
    
    open override func prepare() {
        super.prepare()
        isMotionEnabled = true
        motionNavigationTransitionType = .fade
        guard let v = navigationBar as? NavigationBar else {
            return
        }
        
        v.backgroundColor = .darkGray
        v.depthPreset = .depth5
        v.dividerColor = Color.grey.lighten2
    }
}`

Sorry if i ask much questions because i am not yet professional and i want to be a professional in one day.
Thank for your valuable help.

**Comment by daniel-jonathan** [comment]
@SamboVisal Hey! Why did you close this? Did you solve your problem?
