### ISSUE TITLE
Error Launching Sample CollectionView

### ISSUE THREAD

**Issue by nflahavan** [CosmicMind/Samples#127]
I am trying to launch the programmatic sample CollectionView app. App builds, but throws this error when launched.

2018-11-14 11:42:57.340763-0800 CollectionView[36436:771100] *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.93.8/UICollectionViewData.m:447
2018-11-14 11:42:57.344331-0800 CollectionView[36436:771100] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x6000031815e0> {length = 2, path = 0 - 0}'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e1461bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010c359735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e145f42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010bd5c877 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   UIKitCore                           0x0000000116a3ddfa __45-[UICollectionViewData validateLayoutInRect:]_block_invoke + 1354
	5   UIKitCore                           0x0000000116a3d379 -[UICollectionViewData validateLayoutInRect:] + 2483
	6   UIKitCore                           0x0000000116a0b00e -[UICollectionView layoutSubviews] + 260
	7   UIKitCore                           0x0000000117698795 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1441
	8   QuartzCore                          0x000000010e8d8b19 -[CALayer layoutSublayers] + 175
	9   QuartzCore                          0x000000010e8dd9d3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	10  QuartzCore                          0x000000010e8567ca _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 342
	11  QuartzCore                          0x000000010e88d97e _ZN2CA11Transaction6commitEv + 576
	12  UIKitCore                           0x00000001171c92d0 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 139
	13  CoreFoundation                      0x000000010e0ab62c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	14  CoreFoundation                      0x000000010e0aade0 __CFRunLoopDoBlocks + 336
	15  CoreFoundation                      0x000000010e0a5654 __CFRunLoopRun + 1284
	16  CoreFoundation                      0x000000010e0a4e11 CFRunLoopRunSpecific + 625
	17  GraphicsServices                    0x00000001126af1dd GSEventRunModal + 62
	18  UIKitCore                           0x00000001171ae81d UIApplicationMain + 140
	19  CollectionView                      0x000000010b510e34 main + 68
	20  libdyld.dylib                       0x000000010ffbc575 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by daniel-jonathan** [comment]
@OrkhanAlikhanov Let's confirm this issue.

**Comment by vineet-devin** [comment]
May I know how you guys fixed this issue? I am facing same issue in my app.

**Comment by daniel-jonathan** [comment]
Can you share your setup code? @vineet-devin
