### ISSUE TITLE
ToolbarController Sample not works

### ISSUE THREAD

**Issue by 22Round** [CosmicMind/Samples#128]
Using Swift 4.2 & xCode 10
I am testing ToolbarController sample project and it throws error on `StatusBarController` line 114

> Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

can you check it?

**Comment by 22Round** [comment]
sorry false alert it was my fault

**Comment by daniel-jonathan** [comment]
@22Round no worries, thank you!
