### ISSUE TITLE
No such module 'Material' in Xcode 8.1

### ISSUE THREAD

**Issue by sudhi001** [CosmicMind/Samples#14]
~/Downloads/Samples-master/Material/Programmatic/Card/Card/ViewController.swift:32:8: No such module 'Material' in Xcode 8.1

**Comment by chinamcafee** [comment]
Step1: ./install_all_pods.sh
Step2: import the Card project in Xcode 8.1 only. e.x: File-open-Samples/Material/Programmatic/Card/Card.xcworkspace
Step3: Run and Enjoy.

**Comment by daniel-jonathan** [comment]
Going to look into this today.

**Comment by daniel-jonathan** [comment]
Did you have the CosmicMind workspace opened when you tried opening the sample project directly ? I can't reproduce this issue.

**Comment by daniel-jonathan** [comment]
Make sure you are opening the project workspace itself, not the CosmicMind one, that is for manual addition of frameworks :) If you continue to have issues, please reopen or create a new issue. Thank you!

**Comment by MacMeDan** [comment]
Hey @danieldahan when you say 
> that is for manual addition of frameworks
How do you accomplish that? I was able to do it once where I used the Sample.workspace and remember having to add something to get project to build there but I cannot for the life of me remember how to do it.

**Comment by daniel-jonathan** [comment]
@MacMeDan GitHub (git clone) is for manual addition of the frameworks. I thought you are using Carthage? Here are the [3 installation methods](https://www.cosmicmind.com/danieldahan/lesson/6). You can also drag the project into the Samples workspace and then add the frameworks into the projects you are wanting to use.

**Comment by MacMeDan** [comment]
Yes I am using Carthage I was trying to get the Samples app up and running so I could look at how things work there. I think I figured out what I was mission. I needed to download the `Material` project and build the `Motion` and `Material` targets. Take those frameworks and add them manually to each project in the `Samples` project.

**Comment by daniel-jonathan** [comment]
@MacMeDan yes that is exactly correct.

**Comment by Beyond-Chao** [comment]
I update my pod to latest version that solve my problem!

**Comment by daniel-jonathan** [comment]
Awesome! @Beyond-Chao
