### ISSUE TITLE
TextField build failed using Material 2.3.4

### ISSUE THREAD

**Issue by chinamcafee** [CosmicMind/Samples#16]
When I tried to build TextField Sample using Materail 2.3.4, it failed and Xcode 8 report that there had an error in Material+UIImage.swift at line 309. The information as follows:

"Material+UIImage.swift:309:30: Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions"

**Comment by daniel-jonathan** [comment]
There is a fix being released for this very shortly. Please follow this issue: https://github.com/CosmicMind/Material/issues/591
