### ISSUE TITLE
Does leftview could set up active&normal color in Textfield ?

### ISSUE THREAD

**Issue by chinamcafee** [CosmicMind/Samples#17]
I wonder if there has a property of leftview to set up active&normal color in Textfield, does it could only set an image with fixed color?

**Comment by daniel-jonathan** [comment]
This sounds like a good feature request and one I can add when I release the updates for TextField. I am going to close this and link the issue to Material directly. Here is the issue https://github.com/CosmicMind/Material/issues/594
