### ISSUE TITLE
use pagetabbar on top 

### ISSUE THREAD

**Issue by mkaya93** [CosmicMind/Samples#18]
Hello,

I want to use page tabbar on top but I couldn't move it to the top .

How can I make it ? 

Thanks

**Comment by daniel-jonathan** [comment]
Hey,

You can use the `pageTabBarAlignment` property and set it to `.top`. 

:) All the best!

**Comment by mkaya93** [comment]
thank you danieldahan also how can I use it without rootviewcontroller ? 
(My viewcontroller loading by tabbar controller how can I set it ? )

**Comment by daniel-jonathan** [comment]
Yes, if you use the `TabBar` view, you can place it anywhere you like. If you are using `Layout`, you can do this:

``` swift
let tabBar = TabBar()
// Add buttons...
view.layout(tabBar).top().horizontally()
```

Hope that helps :)

**Comment by mkaya93** [comment]
![25-notifications](https://cloud.githubusercontent.com/assets/6665723/20248319/39ea66d0-a9ea-11e6-94e9-e97e156bd2a2.png)

I'm talking about this. How can I will call page tabbar on this scenario ?

**Comment by daniel-jonathan** [comment]
At the current moment, there really is only two options:
1. Use the PageTabBarController, and that means using the `rootViewController`,
2. Construct the view yourself. Any suggestions I give you when it comes to creating it yourself will be much harder and more error prone than the `PageTabBarController` option.

Possibly, I can help you move your current UIViewController to the PageTabBarController using the rootViewController. It is really easy usually.

**Comment by mkaya93** [comment]
@danieldahan so how can I make it using via storyboard. 

![ekran resmi 2016-11-20 22 12 43](https://cloud.githubusercontent.com/assets/6665723/20465454/1bcd8f34-af66-11e6-92ae-2eaa8275eb06.png)

**Comment by daniel-jonathan** [comment]
I think making it using Storyboards is going to be complex and really not my speciality. I do everything programmatically, so I don't face limitations that Storyboards impose.

**Comment by mkaya93** [comment]
So, I'm still didn't understand how can I add page tabbar to this scenario

**Comment by daniel-jonathan** [comment]
I believe if you want to do it with Storyboards you need to construct the entire thing using the pieces available in Material, such as `TabBar`.

**Comment by mkaya93** [comment]
okay how can I do that without storyboard ? 

I'm just trying to figure out how can I implement it.

**Comment by daniel-jonathan** [comment]
I will be back in a few hours, I will work with you to get it up and running nicely. Let's chat on [Material Gitter](https://gitter.im/CosmicMind/Material) :)
