### ISSUE TITLE
Issue building projects using CocoaPods. 

### ISSUE THREAD

**Issue by uutkarshsingh** [CosmicMind/Samples#19]
I am trying to run the sample programs that are present in this repo but I am facing problems
According to the installation instructions mentioned in the link I have executed the shell script but I get the following errors on command line. The cococapods version is 1.1.0.beta.1
https://github.com/CosmicMind/Samples/wiki/Installation
I
![screen shot 2016-11-15 at 4 09 05 pm](https://cloud.githubusercontent.com/assets/3918254/20302583/dc5ac0c2-ab4d-11e6-8298-c0a0113e675c.png)

Then I tried to go the folder BottomNavigationController and then did "pod install" . It installed the dependencies but when I open xcworkspace file I get many errors. I am using Xcode 8.1.![screen shot 2016-11-15 at 4 12 36 pm](https://cloud.githubusercontent.com/assets/3918254/20302702/5e3e90f0-ab4e-11e6-8fb2-e79812a8dc74.png)
Please help. Thanks

**Comment by daniel-jonathan** [comment]
What version of CocoaPods are you running?

**Comment by uutkarshsingh** [comment]
1.1.0.beta.1

**Comment by jeandavid** [comment]
Having the same issue. With CocoaPods version 1.0.0

**Comment by uutkarshsingh** [comment]
hi @danieldahan 
I am not aware of internal workings of Cocoapods but should'nt the Project itself show the version number in tags or the branch on github which should show 2.0?? It is not showing as shown in the following image
![screen shot 2016-11-16 at 1 51 07 pm](https://cloud.githubusercontent.com/assets/3918254/20339826/7e6d6b88-ac04-11e6-8a5d-5493642d1547.png)
![screen shot 2016-11-16 at 1 51 02 pm](https://cloud.githubusercontent.com/assets/3918254/20339827/80f505aa-ac04-11e6-967b-9d7e6caab5e9.png)

**Comment by daniel-jonathan** [comment]
The samples repo is independent of the frameworks, Material, Graph, and Algorithm. They always represent the latest release, but could be updated many times as samples are added and modified. In this case, CocoaPods is a separate package manager, and its versioning and correctness is another matter entirely. 

So if you look at your first error message, you will see 'inout' is not allowed before a parameter... This is a Swift 3 feature, and leads me to think you may not be using Swift 3, which is what all the frameworks support and are maintained under. 

Can you confirm you are using Swift 3, or another version?

**Comment by daniel-jonathan** [comment]
I haven't heard from you, so if this is still an issue, please reopen or create a new issue :) Thank you!
