### ISSUE TITLE
How to dynamically set TableViewCell with Cards

### ISSUE THREAD

**Issue by daniel-jonathan** [CosmicMind/Samples#2]
This is a followup issue based on an original issue in Material https://github.com/CosmicMind/Material/issues/554

**Comment by hishambakr** [comment]
Many thanks. I will try it in weekend and feedback you

**Comment by daniel-jonathan** [comment]
No worries :) I will be updating the project tomorrow, so you should be good with a nice sample for the weekend. All the best!

**Comment by daniel-jonathan** [comment]
Hey, I finished this sample [CardTableView](https://github.com/CosmicMind/Samples/tree/development/Advanced/CardTableView). It is in the development branch.

**Comment by hishambakr** [comment]
why project has compilation errors ?

**Comment by hishambakr** [comment]
cells height are not displayed correctly

**Comment by daniel-jonathan** [comment]
Please checkout [CardTableView](https://github.com/CosmicMind/Samples/tree/master/Graph/CardTableView) :)
