### ISSUE TITLE
Make an Editor sample project. 

### ISSUE THREAD

**Issue by daniel-jonathan** [CosmicMind/Samples#20]
Original issue https://github.com/CosmicMind/Material/issues/598

Make a sample project using the new `Editor` component.

**Comment by theolof** [comment]
Hi!

I got the Editor to work mostly. One issue I'm having: I cannot show a placeholder like I did in TextView.

I've tried
`editor.placeholderText = NSLocalizedString("post.add", comment: "Post to your followers")`
and
`editor.textView.placeholderText = NSLocalizedString("post.add", comment: "Post to your followers")`
but nothing shows.

**Comment by daniel-jonathan** [comment]
I haven't added the placeholder code to the Editor. It was only a soft release so far, and the full release is scheduled this week.

**Comment by theolof** [comment]
Great, that explains it 😀
