### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by uutkarshsingh** [CosmicMind/Samples#21]
Hi,
I am sorry I could not get back at the question you asked in the earlier issue,so I have reopened th issue.
This is the following status and more information
**Xcode 8.1
Cocoapods 1.1.1**

Now I try to run the script 'install_all_pods.sh'
which throws a lot of errors

![screen shot 2016-11-18 at 11 58 07 am](https://cloud.githubusercontent.com/assets/3918254/20420897/86ffcda8-ad86-11e6-9f7a-641ef96a3640.png)

Then I go inside the project
CosmicSamples/Material/Programmatic/Button
Then I run '**pod install**'
I get the following error
![screen shot 2016-11-18 at 11 59 29 am](https://cloud.githubusercontent.com/assets/3918254/20420895/85017d4e-ad86-11e6-89cc-35174d60558f.png)

I do what the error message tells me yet no change in the error message.
I guess that the something bad has happened but still I open the .xcworkspace and try to run then I get
"**No such module 'Material'** " error 
This is the screenshot for your reference

![screen shot 2016-11-18 at 12 02 20 pm](https://cloud.githubusercontent.com/assets/3918254/20421025/6237490a-ad87-11e6-8df1-9bf026f937de.png)

**Comment by daniel-jonathan** [comment]
Hey, I ran the latest and all seems to work. I would do a fresh git clone, and clear your CocoaPods cache, `pod cache clean --all`. 

Also, make sure you have the latest CocoaPods with `sudo gem install cocoapods --pre`. 

Finally, ensure that you have the correct permissions set on the Samples directory that allow your user to execute the correct commands. 

If the issue persists, please reopen or create a new issue :)
