### ISSUE TITLE
PageTabBarController without adding as rootViewController

### ISSUE THREAD

**Issue by viral-etymon** [CosmicMind/Samples#23]
Can I prepare and config PageTabBarController without setting it in AppDelegate as rootViewController? If Yes can someone provide me sample code?

**Comment by daniel-jonathan** [comment]
Yes, you would use the same setup that you would in the AppDelegate. 

```swift
AppPageTabBarController(viewControllers: [RedViewController(), GreenViewController(), BlueViewController()], selectedIndex: 0)
```

This will work anywhere :)

**Comment by viral-etymon** [comment]
Yes I got it that but my scenario is bit different.

In root of appdelegate I have have NavigationController and then I want to add PageTabBarConroller in that. And I prefer to do this via storyboard.

Below code is working for me if I do it in AppDelegate

```
let navController:AppNavigationController = AppNavigationController(rootViewController: MVPageTabBarController(viewControllers: [movieVillaViewController, upcomingViewController], selectedIndex: 0))
window = UIWindow(frame: UIScreen.main.bounds)
window!.rootViewController = navController
window!.makeKeyAndVisible()
```

Now what I want is don't want to write anything in AppDelegate. I have added NavigationController to storyboard, set it's custom class with my AppNavigationController.

Now I want to add rootViewController to NavigationViewController. How can I do this?

**Comment by daniel-jonathan** [comment]
Here is [NavigationController Storyboard Sample](https://github.com/CosmicMind/Samples/tree/master/Material/Storyboards/NavigationController) that should show you how to do this.

**Comment by xradeon** [comment]
Using PageTabBarController from storyboard crashes on PageTabBarController init?(coder aDecoder: NSCoder)

**Comment by daniel-jonathan** [comment]
The `PageTabBarController` shouldn't be set from a Storyboard, not currently at this time. Can you send me a sample of what you have done, so I can test it?
