### ISSUE TITLE
NavigationController with status bar

### ISSUE THREAD

**Issue by viral-etymon** [CosmicMind/Samples#24]
When I am implementing NavigationController it hides status bar above.

![simulator screen shot 23-nov-2016 7 43 13 pm](https://cloud.githubusercontent.com/assets/23634389/20564878/1f7dd110-b1b5-11e6-883c-00c443268985.png)

Will you please help me how can I enable it to show again???

**Comment by daniel-jonathan** [comment]
Yes, what is the version of Material you are using, and please share your setup code.

**Comment by daniel-jonathan** [comment]
I just tried the latest sample, looks to be working. 

<img width="374" alt="screen shot 2016-11-23 at 5 30 06 pm" src="https://cloud.githubusercontent.com/assets/9982123/20582003/8828ff22-b1a2-11e6-824e-62494fe15009.png">

**Comment by viral-etymon** [comment]
Hi, 

I am using 2.3.10 version of Material. And yes I am doing nothing just replacing sample code which is available on github.

My Sample code is below:
In AppDelegate:

`var window: UIWindow?`
in didFinishLaunchingWithOptions method
```
window = UIWindow(frame: Screen.bounds)
window!.rootViewController = AppNavigationController(rootViewController: RootViewController())
window!.makeKeyAndVisible()
```
AppNavigationController is

```
import UIKit
import Material

class AppNavigationController: NavigationController {
    open override func prepare() {
        super.prepare()
        guard let v = navigationBar as? NavigationBar else {
            return
        }

        v.depthPreset = .none
        v.dividerColor = Color.grey.lighten3
    }
}
```

Nothing change in RootViewController

[RootViewController](https://github.com/CosmicMind/Samples/blob/master/Material/Programmatic/NavigationController/NavigationController/RootViewController.swift)

Thanks

**Comment by daniel-jonathan** [comment]
Are you using the Sample project directly ? Could you confirm that you do not have hide status bar in the project settings. I will double checkout production code.

Also, please try upgrading to the latest.

**Comment by viral-etymon** [comment]
No I am not using sample project. I am integrating it in my project by following sample project given. I have crossed check that hide status bar is not checked. Ok I try to upgrade it to latest and let you know. 

Thanks

**Comment by daniel-jonathan** [comment]
Thank you :)

**Comment by daniel-jonathan** [comment]
Hey, I haven't heard from you. So I will close this issue, and if you need, please reopen or create a new one :) Thank you!

**Comment by viral-etymon** [comment]
Sorry for this... Yes I am also wrapping some other task on hand so didn't get any chance. If I found any difficulty then I will ask you. Thanks for your time :-)

**Comment by cartickn** [comment]
@danieldahan 

In the sample project the Info.plist file has the following key set-up...

`View controller-based status bar appearance = NO`

If you remove this key then you can reproduce the problem with the sample project as well.

**Comment by tuxfamily** [comment]
Same here.

My workaround is to add
```swift
override public var preferredStatusBarStyle: UIStatusBarStyle {
        return UIStatusBarStyle.default
}
```

To the custom NavigationController class.

Also, in the storyboard, make sure that your navigation controller uses the custom class AND that  `Inherit Module From Target` is checked (was unchecked for me and the above workaround was not working).

Caution: for this to works `View controller-based status bar appearance` must be set to `YES` or not defined.
