### ISSUE TITLE
Material Search Bar within a Navigation Controller

### ISSUE THREAD

**Issue by kaifucious** [CosmicMind/Samples#25]
Hello! Is there an example of how to place the Material Search Bar in a Navigation Controller, inside of a Tab Bar Controller? So basically, a setup like Facebook mobile, but instead of their version of the search bar, it would show the Material search bar. I didn't see any examples, so I figured Id ask

**Comment by daniel-jonathan** [comment]
Hey, You should be able to add a `SearchBar` to the `navigationItem` for the `NavigationController`. 

Please update to [Material 2.3.17](https://github.com/CosmicMind/Material/releases/tag/2.3.17), and then try the following code. 

```swift
let searchBar = SearchBar()

navigationItem.centerViews = [searchBar]
navigationItem.contentViewAlignment = .full // Tells the NavigationController to spread the contentView (centerViews) across all the available space. 

// Example buttons.
navigationItem.leftViews = [menuButton]
navigationItem.rightViews = [starButton, searchButton]
```

<img width="375" alt="screen shot 2016-11-24 at 11 33 51 am" src="https://cloud.githubusercontent.com/assets/9982123/20607242/42531a10-b23c-11e6-9e91-1ed8d0b936db.png">
<img width="375" alt="screen shot 2016-11-24 at 11 34 15 am" src="https://cloud.githubusercontent.com/assets/9982123/20607243/42536650-b23c-11e6-9cfc-b462b9558a11.png">

That should work :)

**Comment by kaifucious** [comment]
Okay, then I must be missing something because with this code:

**Comment by daniel-jonathan** [comment]
Your code isn't visible, can you share again please?

**Comment by kaifucious** [comment]
self.searchBar = SearchBar()
self.navigationItem.centerViews = [self.searchBar]
self.searchBar.delegate = self
        
self.navigationItem.contentViewAlignment = .full
var buttons = [IconButton]()
buttons.append(IconButton(image: Icon.cm.menu))
buttons.append(IconButton(image: Icon.cm.moreVertical))
self.navigationItem.leftViews = buttons

Nothing appears on the navigation bar at all

Heres what a po of the search bar produces:
<Material.SearchBar: 0x7faee5402ae0; frame = (0 0; 0 49); autoresize = W; layer = <CALayer: 0x6080000226a0>>


![simulator screen shot nov 24 2016 2 14 19 pm](https://cloud.githubusercontent.com/assets/8779059/20610567/5b907464-b250-11e6-8225-5797320eaf9e.png)

**Comment by daniel-jonathan** [comment]
Where is this code placed? Is it in the `rootViewController` of the `NavigationController`?

**Comment by kaifucious** [comment]
Yes it is, in -viewDidLoad

**Comment by daniel-jonathan** [comment]
That is strange then. Would you be able to share a sample project with me at support@cosmicmind.com?

**Comment by kaifucious** [comment]
Sure, I'll send over exactly what I'm looking at in a few minutes! :)

**Comment by daniel-jonathan** [comment]
Thank you :)
