### ISSUE TITLE
Best practice to use controls

### ISSUE THREAD

**Issue by viral-etymon** [CosmicMind/Samples#26]
All given controls are great individually but how to implement when all controls are come to gather?

Like in my app I have status bar + Tool bar + page tab bar. And each tab contain collection view. To achieve above I have done below code.
**AppDelegate**

```
var window: UIWindow?
    
    lazy var movieVillaViewController: MovieVillaViewController = {
        return UIStoryboard.viewController(identifier: "MovieVillaViewController") as! MovieVillaViewController
    }()
    
    lazy var upcomingViewController: UpcomingViewController = {
        return UIStoryboard.viewController(identifier: "UpcomingViewController") as! UpcomingViewController
    }()
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {                
        let viewControllers = [playingNowViewController, upcomingViewController] as [UIViewController]
        
        let pageTabBarController = MVPageTabBarController(viewControllers: viewControllers, selectedIndex: 0)
        let toolbarController = AppToolbarController(rootViewController: pageTabBarController)
               
        window = UIWindow(frame: UIScreen.main.bounds)
        window!.rootViewController = toolbarController
        window!.makeKeyAndVisible()
        
        return true
    }
```
So my view is looking somthing like below

![simulator screen shot 25-nov-2016 3](https://cloud.githubusercontent.com/assets/23634389/20622192/af14b172-b327-11e6-9936-a08b1a93af12.png)

Now when user click on blue search button. It should open new view with only search bar on top and containing collection view under it, and don't want toolbar, page tab bar control.

Issue is in given example on git hub for search bar is added in AppDelegate as rootViewController but I do have some other controls as rootViewController as you can see above. 

So can you please suggest best way how to implement these great controls which can work with each other.

May be my question is silly to you but I am beginner in iOS.

Thanks

**Comment by daniel-jonathan** [comment]
I think your question is great :) I will writeup a note for you and post it later today.

**Comment by daniel-jonathan** [comment]
Hey, sorry for any delays. I have been writing an article on helping to build application architecture using Material. This will provide all the insight you need. I am almost done and will post it right away.

**Comment by viral-etymon** [comment]
Thank you very much. I am waiting eagerly :-)

**Comment by daniel-jonathan** [comment]
I will be done this article within the next couple days, but you can follow along as I go: [Application Architecture With Material](http://www.cosmicmind.com/danieldahan/application-architecture-with-material). I will keep this issue open until then :)

**Comment by viral-etymon** [comment]
Thank you. You are doing great things. I am following given link. :-)

**Comment by daniel-jonathan** [comment]
More updates coming today for this article :)

**Comment by viral-etymon** [comment]
Sorry but I didn't able to see any update. Am I missing something?

**Comment by daniel-jonathan** [comment]
Sorry, I didn't have a chance to push an update just yet. I was caught up in a couple issues that needed to be taken care of. If all goes well today, I will have more up there. Sorry for that :)

**Comment by daniel-jonathan** [comment]
Now that you have the link, I am going to close this issue. And if you would like to chat, let's move this to the [Material Gitter](https://gitter.im/CosmicMind/Material) channel.

**Comment by daniel-jonathan** [comment]
@viral-etymon Hey, sorry for the delay. The article has been updated http://www.cosmicmind.com/danieldahan/application-architecture-with-material :) Let me know what you think and I could add more, or write another. Thank you!

**Comment by viral-etymon** [comment]
Hi It is good article which explain how to work with multiple RootControllers. One thing I want to suggest which help many, if you can provide working sample of code as many are looking for code which fits to their application. Like in my scenario, I have used ToolBar and under that TabBar. Now If I want only SearchBar, then what the actual changes I need to do in my working APP? 

Let me know if I am going other way.

Thanks

**Comment by daniel-jonathan** [comment]
This is kind of tricky, as there would be many situations that I would need to cover. If you would like, let's chat in [Material Gitter](https://gitter.im/CosmicMind/Material) :) Thank you! I love the feedback.

**Comment by donghd** [comment]
@danieldahan : I am using Navigation Drawer Controller + Tool Bar + Tab Bar 
When user click Search button of Tool Bar, i would like it works as Search Bar Controller (as Search sample), therefore I would like to check your below guide : http://www.cosmicmind.com/danieldahan/application-architecture-with-material
But I cannot access that file :( ! Where you put that file or are there any guide about that implementation?
Thanks,

**Comment by daniel-jonathan** [comment]
@donghd I am working on an education center which would help greatly in this situation. As of now, I can only lend tips. The previous article was removed for various reasons. So before I offer a suggestion, I have a question. Do you want the TabBar to be visible when you navigate from the ToolbarController?

**Comment by donghd** [comment]
@danieldahan : I would like to make iOS somehow same as my Android app, when click Search button of Tool bar, it does not navigate to other screen, it still on that screen with current data, but tool bar's UI need to display Search box by relacing Toolbar's title (for ex), and work like as Search sample' Search bar functionality. So I still want TabBar be visible ... , incase each Tab Bar's data has many rows, it will be quite useful to filter data in each Tab Bar.
Thanks,

**Comment by daniel-jonathan** [comment]
@donghd please follow this issue: https://github.com/CosmicMind/Samples/issues/101, I will make a sample.

**Comment by donghd** [comment]
Thanks you for quick action! I will follow and looking forward to the sample.
