### ISSUE TITLE
Error in Samples/AppToolbarController

### ISSUE THREAD

**Issue by peersocialdeal** [CosmicMind/Samples#3]
Hi,

I found something in prepareStatusBar() {}

file: Programmatic/ToolbarController/ToolbarController/AppToolbarController.swift
line: 65

I think it's supposed to be:
`statusBarController?.statusBar.backgroundColor = Color.blue.darken3`
instead of:
`statusBar.backgroundColor = Color.blue.darken3`

Thanks

**Comment by daniel-jonathan** [comment]
There isn't an error, the `ToolbarController` inherits from the `StatusBarController`. This is done to provide the spacing above the Toolbar and behind the statusBar, when it is a controller. 

`open class ToolbarController: StatusBarController`

Are you getting an error of some sort? Also, this is for versions 2.2.*.
