### ISSUE TITLE
Tab Control in between of another view

### ISSUE THREAD

**Issue by viral-etymon** [CosmicMind/Samples#30]
Hi I am not getting way to put tab control inside other view.

![materialtabinbetween](https://cloud.githubusercontent.com/assets/23634389/21314041/edf5b994-c61a-11e6-94c9-baf81276167d.png)

Seeking your help. Thanks

**Comment by daniel-jonathan** [comment]
[Linked StackOverflow Question](http://stackoverflow.com/questions/40970879/cosmicmind-material-how-do-i-implement-pagetabbarcontroller-without-using-appde) 

Hi, yes there is a way. The `PageTabBarController` is inherited from a `UIViewController`, which allows you to add it as a child of any other UIViewController. That said, you just gave me a great idea. I am going to make a new UIViewController that allows you to add as many child UIViewControllers, which will make this super easy to do. I will make this as a *Feature Request*. 

Until the update, please use the suggested method of adding it as a child UIViewController. Are you familiar with how to do that?

**Comment by viral-etymon** [comment]
Thanks,
No I am not familiar with how to add UIViewController as child but will find my way. If there is any problem will let you know. If you have any link on hand then please post that otherwise ok.

Thanks again

**Comment by daniel-jonathan** [comment]
No worries, I can help you tomorrow. I am about to sleep. Talk then :)

**Comment by daniel-jonathan** [comment]
@viral-etymon want some help? If you join [Material Gitter](https://gitter.im/CosmicMind/Material) I can help you out :)
