### ISSUE TITLE
Few issues w/XCode 8.2.1

### ISSUE THREAD

**Issue by christaggart** [CosmicMind/Samples#32]
Tried to build the CardTableView sample after running the ``install_all_pods`` script. Wasn't quite able to determine a solution. Running XCode 8.2.1 (8C1002).

* Screen doesn't seem to be resolvable?
```/Samples-master/Graph/CardTableView/CardTableView/CardTableViewCell.swift:110:36: Use of unresolved identifier 'Screen'```

* ```AppDelegate.swift:54:36: Argument labels '(viewController:)' do not match any available overloads```
![image](https://cloud.githubusercontent.com/assets/205751/21446855/c36950ce-c899-11e6-8356-0e77d3bcd89d.png)

**Comment by daniel-jonathan** [comment]
When I look at that file I see this

```swift
let pageTabBarController = AppPageTabBarController(viewControllers: viewControllers)
```

You probably need to update the Samples repo. Give it a shot, and let me know :)

**Comment by daniel-jonathan** [comment]
For this `Screen doesn't seem to be resolvable?` you need to update Material to the latest. If you continue to have any issues, please reopen or create a new one. Thank you :)
