### ISSUE TITLE
Is it possible to setup cards for a list view in the storyboard? or does it have to be done programatically ?

### ISSUE THREAD

**Issue by ty-fleming** [CosmicMind/Samples#34]

**Comment by daniel-jonathan** [comment]
Material has classes that support `TableView` ([CardTableView sample](https://github.com/CosmicMind/Samples/tree/master/Graph/CardTableView)) and CollectionView ([CollectionView sample](https://github.com/CosmicMind/Samples/tree/master/Material/Programmatic/CollectionView). They are subclasses of `UITableView` and `UICollectionView`. So you should be able to add the view object to your storyboard and then change the class name. It should automatically update the Module name. Then I would look at the examples for code snippets that would help you with dynamic sizing for TableView and CollectionView objects. 

Below is an example of adding buttons with storyboards. 

<img width="839" alt="screen shot 2016-12-30 at 7 01 16 pm" src="https://cloud.githubusercontent.com/assets/9982123/21574938/b16050ce-cec2-11e6-8c56-1f941ef0d596.png">

**Comment by ty-fleming** [comment]
Thank you very much for your quick response!!!! Much appreciated!

**Comment by daniel-jonathan** [comment]
Cool, I am closing this issue for now. If you continue to face an issue, please reopen or create a new one :)
