### ISSUE TITLE
icons on tabbarItem

### ISSUE THREAD

**Issue by helderalvesoliveira** [CosmicMind/Samples#36]
Hello everyone,

how can add icons on item tabs (pageTab...), and remove title text?

thanks very much.

**Comment by daniel-jonathan** [comment]
Hey :) 

Have you seen the [PageTabBarController sample](https://github.com/CosmicMind/Samples/tree/master/Material/Programmatic/PageTabBarController) project ?

In each view controller, you want to add at the initialization phase the `PageTabBarItem` setup. 

```swift
import UIKit
import Material

class RedViewController: UIViewController {
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        preparePageTabBarItem()
    }
    
    init() {
        super.init(nibName: nil, bundle: nil)
        preparePageTabBarItem()
    }
    
    open override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = Color.red.base
    }
}

extension RedViewController {
    fileprivate func preparePageTabBarItem() {
        pageTabBarItem.title = "Red"
        pageTabBarItem.titleColor = Color.blueGrey.base
    }
}
```

If you have any further issues, please reopen or create a new issue :)
