### ISSUE TITLE
How to dynamically set TableViewCell with Cards

### ISSUE THREAD

**Issue by hishambakr** [CosmicMind/Samples#4]
Hi,
I am reopenning it as height is not working properly. how to send you screenshot?

**Comment by hishambakr** [comment]
here is the screenshot
http://pho.to/AQ6TS

**Comment by daniel-jonathan** [comment]
It's not pointing at the correct material version. I'll fix that :)

**Comment by hishambakr** [comment]
also please make sure that example is complex enough to show handling. eg different types of cards like PresenterCard and ImageCard
if possible, please add image loaded from internet in card toolbar icons. I did this and found that image take strange sizes when you scroll table view,
I will share my sample code to show issue but i will wait to see your example first to see if your example has these issues or not

**Comment by daniel-jonathan** [comment]
I am not going to show how to load from the internet in this example, but I am going to show how to load the content from Graph, which is a datastore. You can easily swap that out for the example. I am making some tweaks now :)

**Comment by daniel-jonathan** [comment]
Give this sample a try :) [CardTableView](https://github.com/CosmicMind/Samples/tree/master/Graph/CardTableView)

All the best! Please reopen or create a new issue if needed. Thank you!

**Comment by hishambakr** [comment]
many thanks. sorry for being busy last days. i will give it a try in weekend. best wishes :)

**Comment by daniel-jonathan** [comment]
No worries, and I am planning to write a tutorial on how I accomplished it. I will share it with you and I am aiming to have it done in the next couple days.
