### ISSUE TITLE
Why not create one project include all samples?

### ISSUE THREAD

**Issue by anhhtbk** [CosmicMind/Samples#40]
I want to review some samples, but I must build many project.
Why you not create one project include all samples?
Example: Have a main view include list of buttons link to samples.

**Comment by daniel-jonathan** [comment]
I had done that before, and it becomes a lot for a person to find what they are looking for in the code. Also, some samples will conflict with others based on their design. For example, there are many `RootController` types, how would I show that all can be the `window!.rootViewController` in one sample. Also the samples are going to become more robust as I put more of them together to show advanced topics. For example: the `CardTableView` sample is literally a base application one can start from. I hope this helps clear the reasons up for you.
