### ISSUE TITLE
Images in PresenterCard doesn't load first time

### ISSUE THREAD

**Issue by theolof** [CosmicMind/Samples#42]
I'm following the CardTableView sample, and I'm having trouble with showing the images.
Your example doesn't load the images until switching tab and going back.

<img width="733" alt="screen shot 2017-02-06 at 11 57 12" src="https://cloud.githubusercontent.com/assets/14074538/22644833/65a36616-ec64-11e6-8395-004618e1a895.png">

My problem is related I think: I load the images from the network, which makes them appear after a second. The height of the cell is not correctly calculated, so the scroll area in the table view ends up too small.

What I would like (and this actually worked in an earlier version of Material): If I know I'm going to have an image later, set the height of the cell (or card) so it shows up blank but large. When the image is loaded, it just gets added, but the size stays the same (so the table doesn't flicker for the user).

This is how I set the height if I already know that an image is coming:

```
        if a.imageRef != nil {
            presenterImageView.height = imageHeight
        } else {
            presenterImageView.height = 0
        }
        if let image = activityImage {
            presenterImageView.height = image.height
            DispatchQueue.main.async { [weak self, image = image] in
                self?.presenterImageView.fadeTransition(0.6)
                self?.presenterImageView.image = image
            }
        } else {
            presenterImageView.image = nil
        }

```

**Comment by daniel-jonathan** [comment]
Yes you are correct, there is a regression. Fixing it up.

**Comment by daniel-jonathan** [comment]
Hey, you should be able to use [Material 2.4.15](https://github.com/CosmicMind/Material/releases/tag/2.4.15) and the latest `Samples master`. Thanks for reporting this :)

**Comment by theolof** [comment]
Thanks a lot for the fix. It works.
