### ISSUE TITLE
setting ui element inside card.bottomBar.centerViews

### ISSUE THREAD

**Issue by TaiPhamD** [CosmicMind/Samples#43]
bottomBar.centerViews = [label1,label2,label3]

How do I make Label1 length 2x the lenghth of label 3 for example? It seems like the auto layout adjust the label width in equal proportion

**Comment by daniel-jonathan** [comment]
Hey, 

You can set the `Grid` proportion. So first you will need to adjust the `contentView`, which is what is used for the `centerViews`. 

```swift
bottomBar.contentView.grid.axis.columns = 4
```

Then set the labels' Grid columns. 

```swift
label1.grid.columns = 1
label2.grid.columns = 2
label3.grid.columns = 1
```

Give that a try and if you have any issues, please reopen this issue. Thank you :)

**Comment by TaiPhamD** [comment]
thank you for the quick response. That solved exactly what I needed. Now that I know contentView is accessible I can also adjust the interimspacing as well :)
