### ISSUE TITLE
PhotoLibraryController not found

### ISSUE THREAD

**Issue by kaka21garuda** [CosmicMind/Samples#45]
When I tried to subclass my view controller with PhotoLibraryController, it keeps on saying unidentified. Could anyone explain more about PhotoLibraryController class ?

**Comment by daniel-jonathan** [comment]
Hey! 

You need to add the Photos sub spec if you are using CocoaPods. 

```
pod 'Material/Photos', '~> 2.0'
```

:) All the best!
