### ISSUE TITLE
fabButton method not found in Menu class

### ISSUE THREAD

**Issue by kaka21garuda** [CosmicMind/Samples#46]
is the FABMenu class has been changed to Menu()? Because fabButton and fabMenuItems() methods are not found.
`fabMenu.fabButton = fabButton`
`fabMenu.fabMenuItems = [notesFABMenuItem, remindersFABMenuItem]`

my current pod is: `pod 'Material', '~> 2.0'`

**Comment by daniel-jonathan** [comment]
Make sure that you are using Material 2.5+. `Menu` is now `FABMenu`, as a new `Menu` component is in the works :) Please reopen this issue if you need any help. You might need to clear your pod cache if the latest Material is not updated. Thank you!
