### ISSUE TITLE
[PageTabBar] Transition to another page

### ISSUE THREAD

**Issue by RMariowski** [CosmicMind/Samples#47]
How to make transition to another page via code?
So far i have done this by changing access modifier of handlePageTabBarButton from internal to public. However this is for sure not the proper way of doing this.

**Comment by daniel-jonathan** [comment]
Good morning, 

Take a look at the [Sample PageTabBarController project](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/PageTabBarController). Switching between pages is automatically handled for you. If you have any further questions, let me know, I'd be happy to help. Please reopen this issue if you need. Thank you!

**Comment by RMariowski** [comment]
Hi, thanks for your answer.

> Switching between pages is automatically handled for you

Yes, i know. That's why i'm asking how to do this manually. For example i want to switch page by pressing button which is not from tab bar.

Thanks in advance.

**Comment by daniel-jonathan** [comment]
There is an issue for this, to add a feature, I will work on that today and make a release. I will also keep this up and notify you once I am done. Thank you for the clarification.

**Comment by RMariowski** [comment]
> There is an issue for this, to add a feature

Oh, really? I couldn't find similar issue on the main repository (Material) :/
Sorry for taking your time.

>  I will work on that today and make a release. I will also keep this up and notify you once I am done. 

Cool! 👍

**Comment by daniel-jonathan** [comment]
No worries, I will make an update today solving a couple issues and this is one of them :) Thank you!

**Comment by daniel-jonathan** [comment]
You can now use the selectedIndex property to select a tab in [Material 2.6.2](https://github.com/CosmicMind/Material/releases/tag/2.6.2). For example:

pageTabBarController.selectedIndex = 3

All the best!
