### ISSUE TITLE
Transition ViewController in Storyboard

### ISSUE THREAD

**Issue by vinhpd192** [CosmicMind/Samples#50]
Hi all,

I'm new member of this project, I using NavigationDrawerController and implement LeftViewController as UITableViewController.

How to transition to new view when user click on table row item

**Comment by daniel-jonathan** [comment]
Welcome :) 

Take a look at this [Sample NavigationDrawerController](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/NavigationDrawerController) project. You will want to look for [line #62](https://github.com/CosmicMind/Samples/blob/master/Projects/Programmatic/NavigationDrawerController/NavigationDrawerController/LeftViewController.swift#L62). If you need, please reopen the issue. All the best!
