### ISSUE TITLE
how do i manually segue to a view with navdrawer

### ISSUE THREAD

**Issue by ammarnaqvi** [CosmicMind/Samples#51]
I am new to iOS, my app has a login page, and from login page i segue to a new view and i want navdrawer to be displayed there instead of making navdrawer the rootview in appdelegate.

**Comment by daniel-jonathan** [comment]
Hey :)

Although you can segue to a NavigationDrawerController, it is better to set it as the `rootViewController` in the `AppDelegate` and have it be disabled. Your login view controller should be the `rootViewController` of the `NavigationDrawerController`, and once they have logged in, you should transition the `rootViewController` to another view controller of your choice and enable the `NavigationDrawerController`. 

If you want to manually segue to the `NavigationDrawerController`, just do so as you would with any view controller. The `NavigationDrawerController` inherits from `UIViewController`, so all is the same when doing operations like that. If you need any further help, please reopen or create a new issue. Thank you!

**Comment by AmmarNaqvi** [comment]
Hey Daniel,
Since i am new to this I don't know how to disable the NavigationDrawerController. Is there any documentation or such that i can refer to for available methods?

**Comment by AmmarNaqvi** [comment]
Thank you so much for helping out, and this library is beautiful :D 

So i opened up the source to find how i could disable NavigationDrawerController.
but now i am getting this error,  both LoginViewController and RootViewController are UIViewController.
```
Could not cast value of type 'fleethub.LoginViewController' (0x1011b0320) to 'fleethub.RootViewController' (0x1011afd18).
(lldb) 

```
My code:
```
    var window: UIWindow?
    
    lazy var rootViewController: RootViewController = {
        return UIStoryboard.viewController(identifier: "LoginViewController") as! RootViewController
    }()
    
    lazy var leftViewController: LeftViewController = {
        return UIStoryboard.viewController(identifier: "LeftViewController") as! LeftViewController
    }()
    
    lazy var rightViewController: RightViewController = {
        return UIStoryboard.viewController(identifier: "RightViewController") as! RightViewController
    }()
    
    func applicationDidFinishLaunching(_ application: UIApplication) {
        window = UIWindow(frame: Screen.bounds)
        let appNavigationDrawerController = AppNavigationDrawerController(rootViewController: rootViewController,
                                                                         leftViewController: leftViewController,
                                                                         rightViewController: rightViewController)
        window!.rootViewController = appNavigationDrawerController
        window!.makeKeyAndVisible()
    }
```
