### ISSUE TITLE
search bar clarification example

### ISSUE THREAD

**Issue by johndpope** [CosmicMind/Samples#52]
made some headway with tweaking designs on page.
But no so clear on rest of implementation details.
If I want a tableview inside view / how to rig this up?

I dropped in a tableview inside AppSearchBarController

the rootViewcontroller appears to not work.
Am I supposed to nest this in its own navigation controller?
is the back button supposed to pop / dismiss?

            let app = AppSearchBarController(rootViewController: UIViewController())
            
            
            let vc = OnboardingSuperstarsVC()
            let nc = UINavigationController(rootViewController: vc)
            nc.navigationBar.isTranslucent = false
            window?.rootViewController = nc
            window?.makeKeyAndVisible()
            
            nc.present(app, animated: true, completion: { 
                
            })

```
import UIKit
import Material
import Dotzu


class AppSearchBarController: SearchBarController,SearchBarDelegate {
    fileprivate var menuButton: IconButton!
    fileprivate var moreButton: IconButton!
    
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        Notificator.fireNotification(named: kFilterPressedClose)
    }
    
    open override func prepare() {
        super.prepare()
        prepareBackButton()
        prepareSearchBar()
        
      
        self.view.backgroundColor = wweColors.onyx
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        focusingSearchBar()
    }
    
    func focusingSearchBar() {
        
        guard let searchBar = searchBarController?.searchBar else {
            return
        }
        
        DispatchQueue.main.async {
            searchBar.textField.becomeFirstResponder()
        }
        
    }
    
    func reloadData(){
        
    }
    
    
  
    func searchBar(searchBar: SearchBar, willClear textField: UITextField, with text: String?){
         Logger.verbose("text:",text ?? "")
    }
    
    func searchBar(searchBar: SearchBar, didChange textField: UITextField, with text: String?) {
        guard let pattern = text?.trimmed, 0 < pattern.utf16.count else {
            reloadData()
            return
        }
        
        //https://github.com/lazarte/GraphSearch/blob/b8d7ea54a074838acba63f1fe084e71373ccfe77/Search/RootViewController.swift
        /*search.async { [weak self, pattern = pattern] (users) in
            guard let regex = try? NSRegularExpression(pattern: pattern, options: []) else {
                return
            }
            
            var data = [Relationship]()
            
            for user in users {
                if let name = user.object?["name"] as? String {
                    let matches = regex.matches(in: name, range: NSRange(location: 0, length: name.utf16.count))
                    if 0 < matches.count {
                        data.append(user)
                    }
                }
            }
            
            self?.tableView.data = data
        }*/
    }
    
    
}

extension AppSearchBarController {
    func didPressBackButton() {
        
        
//        self.transitionFromRootViewController(self.rootViewController)
        searchBar.textField.resignFirstResponder()
        self.navigationController?.pop()
    }
    fileprivate func prepareBackButton() {
        menuButton = IconButton(image: Icon.cm.arrowBack)
        menuButton.addTarget(self, action: #selector(didPressBackButton), for: .touchUpInside)
    }
    
    
    fileprivate func prepareSearchBar() {
        UIApplication.statusBarBackgroundColor = wweColors.darkLine
        searchBar.clearButton.tintColor = .white
        searchBar.clearButton.backgroundColor = wweColors.blackButtonColor
        searchBar.clearButton.layer.cornerRadius = 15
        searchBar.textColor = .white
        searchBar.textField.font = RobotoFont.medium(with: 20)
        searchBar.delegate = self
        searchBar.textField.keyboardAppearance = .dark
        searchBar.backgroundColor = wweColors.darkLine
        searchBar.placeholderColor = .white
        searchBar.leftViews = [menuButton]
        searchBar.backgroundColor = wweColors.onyx
        searchBar.textColor = .white
        searchBar.tintColor = wweColors.fireEngineRed

    }
}


```

**Comment by johndpope** [comment]
other warts from rootVC usage.

        let vc = UIViewController() // this is a dummy vc so this flow doesn't crash.
        let popupVC = EditableSuperStarsVC(rootViewController:vc) // this subclasses AppSearchBarController
        let nc = UINavigationController.init(rootViewController: popupVC)
        nc.navigationBar.isTranslucent = false
        self.present(nc, animated: true) {
            
        }



![img_0202](https://cloud.githubusercontent.com/assets/289994/26180875/36b32e8e-3b3a-11e7-9b36-b862ee905b6b.PNG)

**Comment by johndpope** [comment]
I think the 

open func transition(to viewController: UIViewController, duration: TimeInterval = 0.5, options: UIViewAnimationOptions = [], animations: (() -> Void)? = nil, completion: ((Bool) -> Void)? = nil) {

 maybe the answer. 


// thus far I have 
 self.navigationItem.rightBarButtonItem = SearchButtonItem(target: self, action: #selector(self.showSearch))
        
    }
    
    func showSearch(){
        self.perform(#selector(showSearchAfterDelay), with: nil, afterDelay: 0.2)
    }
    
    func showSearchAfterDelay(){
        Logger.verbose("showSearch")
        let app = AppSearchBarController(rootViewController: UIViewController())
        self.present(app, animated: false) {
            
        }
    }

but I can't seem to get the background transparent in the app controller.

**Comment by daniel-jonathan** [comment]
Hey, what version of Material are you using?

If you are using a SearchBarController, the back button would need to come from the UINavigationController. If I am correct, are you trying to add a SearchBar to your UINavigationController?

**Comment by johndpope** [comment]
I'm happy to use SearchBarController out of the box. 
From my view controller 

say 
HomeVC

I want to press a button **present** the search controller - (tiny note - preferably with alpha background so that the results show through) - 


<img width="387" alt="screen shot 2017-05-18 at 2 13 14 pm" src="https://cloud.githubusercontent.com/assets/289994/26217358/13a61848-3bd5-11e7-945a-650c80588b46.png">


```
 let app = AppSearchBarController(rootViewController: UIViewController())  // Q) why do I need to inject empty VC here - otherwise I get a crash.
    self.present(app, animated: false) {
        
    }
```

I habitually present navigation controllers and present them as they give you the header / title as per previous picture. 
eg.

```
 let app = AppSearchBarController(rootViewController: UIViewController()) 
let nc = UINavigationController(rootViewController:app)
    self.present(nc, animated: false) {
        
    }
```



But if I don't do this - it shows ok (need to tweak/hack my tableview offset from top) without this.
![img_0208](https://cloud.githubusercontent.com/assets/289994/26217319/ed202e52-3bd4-11e7-893e-bde3180a6632.PNG)

I'm not clear on the rootViewController part - and how to present this / and there's no tableview inside the AppSearch  - so invariably end up having to rebuild parts. 

most of my code -> here.
https://gist.github.com/johndpope/906c6c0c3bd89bd2baa0e67e3d2644dc

**Comment by johndpope** [comment]
also - when I do present search app - there's a white background I can't seem to override.

**Comment by johndpope** [comment]
- Material (2.6.3):
    - Material/Core (= 2.6.3)
  - Material/Core (2.6.3)

**Comment by daniel-jonathan** [comment]
I will take a look into this later today :)

**Comment by johndpope** [comment]
Thanks Dan. No stress. Am making huge progress.  
If anything - the kink is simply being forced to implement the rootViewController is instantiating class/otherwise I get a crash. If that is the way it's supposed to be - that's cool too - but an updated sample would go a long way.

**Comment by daniel-jonathan** [comment]
Yes, at the current moment, you have to use the `rootViewController` initializer for the SearchBarController. If you don't want to, I would consider adding a SearchBar to any view controller you like, and you will be able to see the code necessary to make that happen in the SearchBarController. It is really simple, so the effort wont be wasteful for you to do that :)

Later today, I will review this issue, but does it seem like there is one still? If not, you can close this. Thanks buddy!
