### ISSUE TITLE
Cannot Utilize AppPageTabBarController

### ISSUE THREAD

**Issue by troy21688** [CosmicMind/Samples#54]
<img width="690" alt="screen shot 2017-05-24 at 9 19 24 pm" src="https://cloud.githubusercontent.com/assets/16483832/26433193/bfc70c18-40c6-11e7-9d4f-824e85b5d6d5.png">

**Comment by daniel-jonathan** [comment]
Hey, Thank you for sharing this. Could you provide more details? What version of Material are you using, and your current setup. It looks like you are using an incompatible version. Also, in the latest version coming out, that line is removed. Thank you!

**Comment by daniel-jonathan** [comment]
Hey, I have not heard from you. So please reopen this issue if it still persists. Thank you!
