### ISSUE TITLE
CardTableView 0 Articles 

### ISSUE THREAD

**Issue by gitton** [CosmicMind/Samples#56]
Working with CardTableView Sample but no card is displayed anything wrong with the setup of the project
Please check
<img width="392" alt="screen shot 2017-06-24 at 12 28 23 pm" src="https://user-images.githubusercontent.com/8217252/27506593-cfdf3d3a-58d8-11e7-8bb7-51559e940acf.png">
 the screenshot for more details

**Comment by daniel-jonathan** [comment]
I'll take a look to see what's wrong. Is this directly from the sample?

**Comment by gitton** [comment]
Yes

**Comment by daniel-jonathan** [comment]
All seems to work. I downloaded the latest sample and did a pod install on that project. I tried it both on an iPhone 6s and the iPhone 7 simulator. Please provide more details or a reproducible project with the error. Thank you!

<img width="804" alt="screen shot 2017-06-25 at 9 52 28 am" src="https://user-images.githubusercontent.com/9982123/27517576-2b151c52-598c-11e7-869c-42d53bf27bd9.png">

**Comment by gitton** [comment]
XCode Version: 9.0 beta 2
**Simulator** 
Device: iPhone 7 Plus version:  iOS 11

**Comment by daniel-jonathan** [comment]
I don't support beta software in the samples.

**Comment by gitton** [comment]
Thank you, It's working in stable version

**Comment by daniel-jonathan** [comment]
Perfect :)
