### ISSUE TITLE
CardTableView sample app missing base classes (won't compile)

### ISSUE THREAD

**Issue by Mozahler** [CosmicMind/Samples#57]
The CardTableView demo sample project won't compile.
Specifically:  **AppFABMenuController**
It is a subclass of **FABMenuController** (in the material framework), which I found a copy of online, 
but that references
**FabButton, FabMenuIem** which are not in the current set of source files in the material framework.

**Comment by daniel-jonathan** [comment]
Please make sure you are using the latest Material and samples, as I do not see any references that are incorrect. Reopen the issue if you need. Thank you!
