### ISSUE TITLE
why is my last icon on Toolbar lost on iphone 6S+ screen?

### ISSUE THREAD

**Issue by quanguyen** [CosmicMind/Samples#58]
Hi,

I get this weird problem when trying to test my app on a larger screen.

======

Originally, I develop my app on an iphone 5S, on which everything is ok

![img_0019](https://user-images.githubusercontent.com/11938078/28513105-f6f67628-707e-11e7-8ab1-42ccf7361386.JPG)

======

With the same code, I tried to run on an iPhone 6S+, my **trash icon** is gone:

![img_0010](https://user-images.githubusercontent.com/11938078/28513155-2aef2538-707f-11e7-95c5-d1ad9048fd14.PNG)

It seems that the `Navigation Bar` on the screen is too wide to fit in the screen. So I review the constraint in `Storyboard`, which is still good.

<img width="579" alt="screen shot 2017-07-24 at 2 40 51 pm" src="https://user-images.githubusercontent.com/11938078/28513357-0f17eea2-7080-11e7-9c7a-d2240a02379c.png">

My `RootNavigationController` is from the sample project:

```
import UIKit
import Material

class RootNavigationController: NavigationController {

    override func prepare() {
        super.prepare()
        
        guard let v = navigationBar as? NavigationBar else {
            return
        }
        
        v.depthPreset = .none
        v.dividerColor = Color.grey.lighten3
    }
    
}
```

Could you show me how I could fit the last icon on the wide screen?

Regards,

**Comment by daniel-jonathan** [comment]
That is so strange, can you send me the code you are using to add the buttons? Or a sample project? I need to see more of what is going on. Thank you!

**Comment by quanguyen** [comment]
Hi Daniel,

Yes this is weird, and takes me a lot of hair.

I'm trying to extract some code portions in my project. Hope this could bring you some clue.



```
class Details: UITableViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        
        prepareMaterial()
    }
}

fileprivate extension Details {
    fileprivate func prepareMaterial() {
        prepareDeleteButton()
        prepareHistoryButton()
        prepareIdentifyButton()
        prepareDownloadButton()
        prepareToolbar()
    }
    
    private func prepareDeleteButton() {
        deleteButton = IconButton(image: UIImage(named: "delete"), tintColor: Color.red.base)
        deleteButton.pulseColor = Color.red.base
        deleteButton.addTarget(self, action: #selector(deleteAccessory), for: .touchUpInside)
    }
    
    @objc
    private func deleteAccessory() {
        // delete actions
    }
    
    
    private func prepareHistoryButton() {
        historyButton = IconButton(image: UIImage(named: "history")!)
        historyButton.pulseColor = Color.blue.lighten3
        historyButton.addTarget(self, action: #selector(showHistory), for: .touchUpInside)
    }
    
    @objc
    private func showHistory() {
        // get history
    }
    
    private func prepareDownloadButton() {
        downloadButton = IconButton(image: UIImage(named: "file-download")!)
        downloadButton.pulseColor = Color.blue.lighten3
        downloadButton.addTarget(self, action: #selector(download), for: .touchUpInside)
    }
    
    @objc
    private func download() {
        // download
    }
    
    private func prepareIdentifyButton() {
        identifyButton = IconButton(image: UIImage(named: "done")!)
        identifyButton.pulseColor = Color.blue.lighten3
        identifyButton.addTarget(self, action: #selector(identify), for: .touchUpInside)
    }
    
    @objc
    private func identify() {
        // identify accessory
    }
    
    private func prepareToolbar() {
        navigationItem.rightViews = [downloadButton, identifyButton, historyButton, deleteButton]
    }
    
}
```

Regards,

**Comment by daniel-jonathan** [comment]
Cool, I will be available to look at this tonight. Thank you for the code and I will follow up.

**Comment by quanguyen** [comment]
I am also actively looking into this problem. Hope that we could find the root cause and update to the community on this great project.

**Comment by quanguyen** [comment]
@danieldahan 

I just separated the issue and replicated in a simplified project in this zip file. Hope you can find something that could help.

I just tested this simplified project:
- On iphone5S: thing is still ok (4 icons displayed)
- On iphone6S+: the last icon (the red trash icon) lost
- On iphone6+ : the last icon (the red trash icon) lost <-- same as on iphone6S+

[LastIconLost.zip](https://github.com/CosmicMind/Samples/files/1184602/LastIconLost.zip)

Have you got any ideas to fix this issue?

Regards,

**Comment by quanguyen** [comment]
@danieldahan 

One thing I notice in my project and the project simplified (`LastIconLost.zip`)  is that: it has a warning about the size of `NavigationBar`:

<img width="1140" alt="screen shot 2017-07-29 at 10 34 11 am" src="https://user-images.githubusercontent.com/11938078/28741895-2551ec26-744b-11e7-9f25-6ab46f34ceda.png">


Clicking the yellow arrow for more details:

<img width="1140" alt="screen shot 2017-07-29 at 10 33 51 am" src="https://user-images.githubusercontent.com/11938078/28741897-2dd58786-744b-11e7-8fd9-52848fc514d6.png">


I did some search and find people suggest to switch the `Simulated Size` to `Freeform` could wipe out the issue. I tried and the warning is gone:

<img width="1139" alt="screen shot 2017-07-29 at 10 35 15 am" src="https://user-images.githubusercontent.com/11938078/28741903-41170fae-744b-11e7-9673-7e85b453931c.png">

(Note that the screen size in my storyboard is set for iphone7)

But the problem is still persist: The red trash icon is only shown in small screen (such as i5S, i6), and lost on the large screen (such as i6S+, i6+).

I think the root cause of this problem is that the navigation bar is wider than the actual screen. But why it could fit on the small screen, not the large screen? How can I narrow the navigation bar's width to the screen's width?

Regards

**Comment by daniel-jonathan** [comment]
Let's follow this issue on using the Material https://github.com/CosmicMind/Material/issues/627 issue.

**Comment by quanguyen** [comment]
Hi Daniel,

I'd like to inform you that I just updated my `Material` to version `2.9.4`, the problem still persists: last icon lost on the large screen such as i6+'s, i6S+'s screen (the last icon is still ok on the small screen: i5S, i6).

Best regards,

**Comment by daniel-jonathan** [comment]
Okay, let's reopen the issue then. Thank you!

**Comment by daniel-jonathan** [comment]
I linked this issue to https://github.com/CosmicMind/Material/issues/627, so please follow that issue for updates on this. Thank you!

**Comment by quanguyen** [comment]
Hi Daniel,

I just retested this issue on Material 2.12.3 -> The problem is gone! i.e. My last icon is not lost!

It just works beautifully!

**Comment by daniel-jonathan** [comment]
Ah amazing! Thank you!
