### ISSUE TITLE
Value of type 'FABButton' has no member 'motion'

### ISSUE THREAD

**Issue by ElyDantas** [CosmicMind/Samples#59]
```
AppFABMenuController.swift
...
extension AppFABMenuController {
    @objc
    open func fabMenuWillOpen(fabMenu: FABMenu) {
        fabMenu.fabButton?.motion(.rotationAngle(45))  <--- had to disable fab rotation to make sample project work.
        print("fabMenuWillOpen")
    }
...
```

**Comment by daniel-jonathan** [comment]
The `motion` function is now `animate` and the `rotateAngle` enum is now `rotate`. Motion was completely rewritten. I need to update the sample, so thank you for this, I will make the change now. Take a look at the documentation if you need any further help :) https://cosmicmind.gitbooks.io/motion/content/animations.html
