### ISSUE TITLE
Add Drawer to a None-Main StoryBoard

### ISSUE THREAD

**Issue by Mahan3340** [CosmicMind/Samples#61]
Hi I'm launching a Storyboard that has a NavigationController inherited from your NavigationController like the code below , how can I initialize left or right controller ? 
I've created a RightDrawerVC.swift controller with xib and want to show is as right menu
(I'm so new to ios developing & I've read your examples but there you have initialized them in delegate 
which i'm launching something else there 

` 
        let storyBoard:UIStoryboard = UIStoryboard(name: "someStoryBoard", bundle: nil)
        let viewController2 = storyBoard.instantiateViewController(withIdentifier: "someStoryBoard")
        
        self.present(viewController2, animated: true, completion: nil)
`

I mean it seams I can just use this library if the drawer is gonna be added to very first Controller , if not how can I do it then ?

**Comment by Mahan3340** [comment]
I finally Found out the solution after hours and I'll paste the code bellow and please add it to your documentation so other newbies like me wont get in trouble :)
1) add a NavigationController to your storyboard ( not always the starting storyboard)
2) create a Class for the NavigationController that extends NavigationDrawerController (Material) 
3) create the left/right Controller's class 
4) create left/right Controller's variable like let drawerVC = MainDrawerVC(nibName: "MainDrawerVC", bundle: nil)
5)  let storyBoard:UIStoryboard = UIStoryboard(name: "MainStoryboard", bundle: nil)
        let mainController = storyBoard.instantiateViewController(withIdentifier: "MainStoryboard")

6) let mainNavigationController = MainNavigationDrawer(rootViewController:mainController,rightViewController:drawerVC)
(Launch From a Controller that doesn't have a NavigationController to a Controller that does have a Navigation Controller)
7)   self.present(mainNavigationController, animated: true, completion: nil)

it maybe obvious but took me hours to find it out , you may close this issue as its solved 👍

**Comment by daniel-jonathan** [comment]
Hey :) I am happy you solved this issue, and if you join the [Material Gitter](https://gitter.im/CosmicMind/Material) it will be much easier for you to give good suggestions like this one. All the best!
