### ISSUE TITLE
Compile Errors in CardTableView Sample (Programmatic)

### ISSUE THREAD

**Issue by muzoman** [CosmicMind/Samples#63]
I get a dozen errors went compiling this sample. git cloned the samples repo, ran the install all pods script, then opened the workspace Xcode rather than project and wham errors. Any ideas how to fix?
<img width="1178" alt="screen shot 2017-08-18 at 16 53 06" src="https://user-images.githubusercontent.com/320009/29466707-cded01be-8435-11e7-8d2b-f45456cdf19a.png">

**Comment by daniel-jonathan** [comment]
What version of Material are you using and have you added the framework to the project either by embedding it or CocoaPods?

**Comment by muzoman** [comment]
I went into the source directory and ran pod install and it pulled in 2.6.3 of Material.

**Comment by daniel-jonathan** [comment]
Try and make sure that the CocoaPods cache is cleared in your local environment.

**Comment by muzoman** [comment]
I ran "pod cache clean --all" then ran pod install again and it pulls in the same Material version 2.6.3.

**Comment by muzoman** [comment]
I see that you've updated the Samples for Material version 2.9.3. Do I need that version of Material in order to get the Samples to compile? I did an experiment by updating the podfile to specify 2.9.3 as the minimum Material version, but pod install just said that version did not exist. So I don't understand how to pull in version 2.9.3 of Material that the project seems to need.

**Comment by daniel-jonathan** [comment]
try `pod update` rather than `pod install`

**Comment by daniel-jonathan** [comment]
and go back to the original Podfile, and try pod update

**Comment by muzoman** [comment]
Yayee! thats fixed it. Thank you Daniel! pod update pulled in 2.9.4 and all is well. Thank you! I'm new to using cocapods, I'm not clear why "pod install" brings in 2.6.3 but pod update installs "2.9.4"?

**Comment by daniel-jonathan** [comment]
I don't personally use CocoaPods, but what I do know is that clearing its cache and calling `pod update` is magic :) Happy it worked out, all the best!
