### ISSUE TITLE
Chips?

### ISSUE THREAD

**Issue by wdcurry** [CosmicMind/Samples#64]
Can somebody explain this feature? There is no mention other than in the feature list, and the sample has no explanation of intent. Is this a simple way to drop, for example, a list of selected contacts for an email, message etc?

When i write my code, i tend to try to drop even a one-liner to signal intention of code, even to just help myself, as i rarely write documentation.

**Comment by daniel-jonathan** [comment]
Hey, sometimes when I am working on a new feature, I will hint at it and add the alpha phase for those that discover it and are interested to explore. I am working on this feature request https://github.com/CosmicMind/Material/issues/850 as part of that effort. Within the next month, I am launching a documentation portal at CosmicMind.com that will provide more insight into the latest and greatest, as well, what is to come :)

If you like, we can chat more at [Material Gitter](http://gitter.im/CosmicMind/Material).

**Comment by wdcurry** [comment]
Thanks Daniel.. i have not yet explore gitter, thank you for that link.. I look forward to integrating some of these efforts into my current project!

**Comment by daniel-jonathan** [comment]
Anytime :) We are here to help.
