### ISSUE TITLE
NavigationDrawer - No example of changing UIViewControllers via segue

### ISSUE THREAD

**Issue by nitishrana28** [CosmicMind/Samples#65]
In the sample for NavigationDrawer, there is no transition example using segue(Items added in MenuViewController). I have integrated the navigation drawer but have no idea how to do that. Also, there is no documentation available for this. From which controller segue should be fired. A working example or an explanatory code would be helpful.

**Comment by daniel-jonathan** [comment]
Sounds good, I will leave this up and put a sample together for you :) Thank you!

**Comment by nitishrana28** [comment]
Any update on the sample ? Since I am using this in my app, I need to integrate many navigations (via segue). So it was kind of urgent.

**Comment by daniel-jonathan** [comment]
@nitishrana28 Hey! I got the documentation tool up and running, so I can help you out, and will write a lesson there. Thank you for your patience.

**Comment by nitishrana28** [comment]
Have you created the sample ? I need that more than anything at the moment. Else I would have to choose different library for this.

**Comment by daniel-jonathan** [comment]
I haven't had a chance yet, generally I never use storyboards, so from my understanding, you would only need to fire the transition method within the segue function call.

**Comment by daniel-jonathan** [comment]
Hey! I haven't heard from you. If this is still an issue, please reopen it. Thank you!

A good person to look at this if you still have an issue is @mohpor :)
