### ISSUE TITLE
Use of unresolved identifier motionModalTransitionType

### ISSUE THREAD

**Issue by harrisonlo** [CosmicMind/Samples#68]
I'm currently in the Transition sample

**Comment by harrisonlo** [comment]
I used the default .sh file to pod install. Turns out that the library is not the newest version so it couldn't find motionModalTransitionType. Solved by pod installing Material to 2.10.2

**Comment by harrisonlo** [comment]
Maybe someone should fix that .sh file?

**Comment by daniel-jonathan** [comment]
@harrison0723 Thank you! The Samples repo is getting a bit of an overhaul to match the documentation we are working on. I will review the .sh file :)

**Comment by daniel-jonathan** [comment]
I have taken note of the `install` script. For now this issue can be closed as the updated version of Material and Motion address the issue. Thank you!
