### ISSUE TITLE
material stretchable table header 

### ISSUE THREAD

**Issue by yasirmturk** [CosmicMind/Samples#69]
how to make the stretchable sticky uitableview header using this library.. i have checked all the samples there is nothing like that?? thanks

**Comment by daniel-jonathan** [comment]
Can you share a link to what you are looking for, or an image?

**Comment by yasirmturk** [comment]
https://www.youtube.com/watch?v=vIeZrhIjApg
https://github.com/gskbyte/GSKStretchyHeaderView

**Comment by daniel-jonathan** [comment]
@adamdahan This is something I know you have solved. Let's make a lesson out of this and possibly an addition to Material.

**Comment by yasirmturk** [comment]
yes please waiting for it.. 
@danieldahan  also there are couple more things like 
- need methods for content alignment in Button class and extensions
- way to use custom transitioning in UIViewController present when overcurrentcontext or modal with transparent background or blur background modal views

**Comment by daniel-jonathan** [comment]
Sounds good :)

**Comment by yasirmturk** [comment]
@adamdahan is busy i guess

**Comment by daniel-jonathan** [comment]
We won’t do it right away, it is in a queue and we will release it as soon as we can :)

**Comment by yasirmturk** [comment]
@danieldahan so you are making a new component for this and should i used any alternate option? `MDCFlexibleHeaderViewController` dont work with `UIImageView` inside...!

**Comment by daniel-jonathan** [comment]
I will need to make a new component or lesson on how to accomplish what you like. As I mentioned it is in a queue to get done :) As for `MDCFlexibleHeaderViewController` I don't know what that is and I cannot comment on its behavior.

**Comment by yasirmturk** [comment]
okay.. waiting for it then.. btw `MDCFlexibleHeaderViewController ` is here 
https://github.com/material-components/material-components-ios/tree/develop/components/FlexibleHeader .. it is very basic though

**Comment by daniel-jonathan** [comment]
Cool, I will check it out :) Thank you!

**Comment by yasirmturk** [comment]
in which project is this example??

**Comment by daniel-jonathan** [comment]
There isn't one yet.

**Comment by yasirmturk** [comment]
Why u closed this? Is there no plan to make this component?

**Comment by daniel-jonathan** [comment]
Ah I didn't see, it was batched closed with some others that I had made over the weekend and did not need up there. Thanks for letting me know.

**Comment by Nitinbond** [comment]
how to make the stretchable sticky uitableview header using this library. I have checked all the samples there is nothing like that?? thanks
![img_20180322_144059 966](https://user-images.githubusercontent.com/11436995/37863133-dd1d762e-2f7e-11e8-9b07-8be4436a2d34.png)
![img_20180322_144134 823](https://user-images.githubusercontent.com/11436995/37863134-dd56ba88-2f7e-11e8-903d-ad1accce7a8f.jpg)

**Comment by daniel-jonathan** [comment]
A note has been made to create this sample. I am closing this to keep issues strictly for active issues. Thank you!
