### ISSUE TITLE
pageTabBarController

### ISSUE THREAD

**Issue by calvinsug** [CosmicMind/Samples#7]
1. how to change Tab bar position from bottom to top ? 
2. Can i add some button with imageView at tabBar ?

**Comment by daniel-jonathan** [comment]
Hey, 
1. use the `open var pageTabBarAlignment = PageTabBarAlignment.bottom` property. 
2. The TabBar takes any buttons you like, they are `UIButton` types, so you should be able to add an image and text as you please. 

:)

**Comment by daniel-jonathan** [comment]
If you have any further questions, please reopen or create a new issue. Thank you!

**Comment by calvinsug** [comment]
1. done
2. i can`t find any button property in pageTabBarItem. I only find buttonType property in pageTabBarItem. Where should i change it?

**Comment by daniel-jonathan** [comment]
Sorry my confusion, I thought you were asking about TabBar. 

``` swift
open class PageTabBarItem: FlatButton {
    open override func prepare() {
        super.prepare()
        pulseAnimation = .none
    }
}
```

The PageTabBarItem inherits from a FlatButton. So that allows you to do this:

``` swift
pageTabBarItem.title = "Red"
pageTabBarItem.titleColor = Color.blueGrey.base
pageTabBarItem.image = Icon.cm.add
```

You can add this code to the [PageTabBarController sample project](https://github.com/CosmicMind/Samples/tree/master/Material/Programmatic/PageTabBarController) to get the following:

<img width="462" alt="screen shot 2016-11-01 at 11 33 32 pm" src="https://cloud.githubusercontent.com/assets/9982123/19917769/c086131e-a08b-11e6-9416-437707808941.png">

I am spending all month writing documentation, so apologies for the lack of documentation currently.

**Comment by calvinsug** [comment]
mmm, if i set image from pageTabBarItem, sometimes my image will cover all of tabBarItem, so the title will be hidden and i can`t change the size and the corner radius. 
[like this screenshoot](http://imageshack.com/a/img922/4666/DaXSY8.png)

i need to show the title [like my app screenshoot](http://imageshack.com/a/img921/6739/9LGgpy.png)

Moreover, i need to use button because i need to fill background color for my thumbUp & thumbDown image [like this image](http://imageshack.com/a/img922/3576/viwoHG.png)

Can i apply the same thing to this TabBar? I really love the Highlight animation if i scroll my contentView, it follows exactly where i scroll (but sadly, in my current app, i can only use hidden/unhide the highlight bar)

**Comment by daniel-jonathan** [comment]
I am going to bed now, tomorrow I will be able to think about what can be done. I will reopen this issue and place it on the project board for tomorrow. I have another issue, [#551](https://github.com/CosmicMind/Material/issues/551) to fix in regards to the PageTabBar... so I can group this all together and come up with something nice.

**Comment by calvinsug** [comment]
nice, i will be waiting for your updates :)

**Comment by daniel-jonathan** [comment]
Didn't forget about this, I will be working on it today and throughout the weekend.

**Comment by daniel-jonathan** [comment]
I will be reworking this all tomorrow. Sorry for any delay.

**Comment by calvinsug** [comment]
Hey, forget about the last issue,    [how to implement this pageTabController without use AppDelegate.swift ?](http://stackoverflow.com/questions/40970879/cosmicmind-material-how-do-i-implement-pagetabbarcontroller-without-using-appde)

I tried this but it causes crash in my app when i try to open that PageTabBarController

`import UIKit
import Material

class MatchViewController: PageTabBarController {
    @IBOutlet weak var containerView: UIView!

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }

    open override func prepare() {
        super.prepare()
        
        self.viewControllers = [MatchDetailViewController(),ListPlayersViewController(),ChatViewController(),selectedIndex: 0]
        
        delegate = self
        preparePageTabBar()
    }`

**Comment by daniel-jonathan** [comment]
At the current moment, storyboards are not well supported for this type of controller. When I rewrite this, I will see if I can make it happen. This is the next feature to rework, which I am hoping to tackle very soon.
