### ISSUE TITLE
View controller not switching after override of tabBar willSelect

### ISSUE THREAD

**Issue by 0xTomDaniel** [CosmicMind/Samples#70]
This is a continuation of issue #67.

I am not able to implement `func tabBar(tabBar: TabBar, willSelect tabItem: TabItem)` without overriding it. I can however implement `func tabBar(tabBar: TabBar, didSelect tabItem: TabItem)` without overriding that one.

The problem is when I override `willSelect` my view controller no longer transitions.

**Comment by mohpor** [comment]
Hi @tomdaniel0x01 
Can you elaborate on the issue?
Are you calling `super.willSelect(...)` in your override of the `willSelect`?

**Comment by daniel-jonathan** [comment]
I am going to issue an update for this, which will have Material use an internal delegate and the external will be for adopters of the TabsController and TabBarDelegate :)

**Comment by 0xTomDaniel** [comment]
@mohpor calling `super.willSelect(...)` did the trick! Thank you.

@danieldahan I do think that would make for cleaner/easier usability of TabsController and TabBarDelegate.

**Comment by daniel-jonathan** [comment]
I am about to make a push right now :) @tomdaniel0x01

**Comment by daniel-jonathan** [comment]
This has now been released in [Material 2.11.0](https://github.com/CosmicMind/Material/releases/tag/2.11.0) :)
