### ISSUE TITLE
How to use TabsController with SnackbarController ?

### ISSUE THREAD

**Issue by ijameelkhan** [CosmicMind/Samples#72]
I am really confused by how the examples creates AppControllers and then make it rootController in appDelegate. 

What I want is how can I use SnackbarController With TabsController ? because a window can only have one rootController. 

I also don't follow we need whole subclassing and then make it root just to show a simple snack bar message ? 

Something like. 

let message = MDCSnackbarMessage()
message.text = "The groundhog (Marmota monax) is also known as a woodchuck or whistlepig."
MDCSnackbarManager.show(message)

**Comment by daniel-jonathan** [comment]
Hey, this is not the correct repository for `MDCSnackbarMessage()`. You are probably using this framework https://github.com/material-components/material-components-ios. Best of luck :)

**Comment by ijameelkhan** [comment]
Sorry. yes I tried that library  but I decided to go with yours. And now I cant do Snackbar in your library. 
Every example that comes with your library makes a sub class and set it as root controller. Thats what confuses me a lot. is there some doc where I can read why you designed it they way you did ?

**Comment by daniel-jonathan** [comment]
Ah... okay, I will write you a description for this :) It will be ready in a couple days.

**Comment by ijameelkhan** [comment]
Yes please. My project has a UINavigationController at root via Storyboard and now I want to use TabbarController Along with Your NavigationController and Snackbar to achieve the UI I want.

**Comment by daniel-jonathan** [comment]
Yup, that will be easy. I will write the docs for you and for everyone :)

**Comment by ijameelkhan** [comment]
Thank you :)

**Comment by ijameelkhan** [comment]
FYI I want to achieve something like this.

1- Navigations Buttons 
2- Tabbars 
3- SideMenuController
4- SnackBarController for quick messages

<img width="524" alt="screen shot 2017-10-13 at 4 07 11 am" src="https://user-images.githubusercontent.com/1882875/31523297-0da59188-afcc-11e7-883d-e3086e8989fd.png">

**Comment by daniel-jonathan** [comment]
@ijameelkhan I am working on the docs, that said, have you looked at this sample? https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/CardTableView

**Comment by ijameelkhan** [comment]
Yes and one other sample and this is what I got 




Here is the code.

window = UIWindow(frame: Screen.bounds)
        
        
        //load splash
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let splashVC = storyboard.instantiateViewController(withIdentifier: "SplashVC") as! SplashVC
        
        
        //wrap inside nav controller
        let navController = AppNavigationController(rootViewController: splashVC)
        
        
        //wrap inside SnackbarController
        let snackBarController = AppSnackbarController(rootViewController: navController)
        
        
        //set it as root
        window!.rootViewController = snackBarController
        window!.makeKeyAndVisible()

**Comment by daniel-jonathan** [comment]
Ah okay. I will finish my lesson on this. What you sent is really not ideal to look at. You can add code blocks to the comments using 3 \` back-ticks like 

\`\`\`swift
let x = 1
\`\`\`

That would produce

```swift
let x = 1
````

**Comment by ijameelkhan** [comment]
Yes and one other sample and this is what I got 

https://user-images.githubusercontent.com/1882875/31620704-608c07a0-b2b1-11e7-8bfa-6e140d479742.png



Here is the code.

```swift
       window = UIWindow(frame: Screen.bounds)
        
        
        //load splash
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let splashVC = storyboard.instantiateViewController(withIdentifier: "SplashVC") as! SplashVC
        
        
        //wrap inside nav controller
        let navController = AppNavigationController(rootViewController: splashVC)
        
        
        //wrap inside SnackbarController
        let snackBarController = AppSnackbarController(rootViewController: navController)
        
        
        //set it as root
        window!.rootViewController = snackBarController
        window!.makeKeyAndVisible()
        
```
and Splash pushes to a new ViewController Called Contacts. here is the code.

```swift
fileprivate func navigateToNextScreen() -> Void {
        
        
        //storyboard
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        
        //create contacts tree VC
        let treeVC = storyboard.instantiateViewController(withIdentifier: "ContactsTreeVC") as! ContactsTreeVC
        
        
        //create contacts tree VC
        let listVC = storyboard.instantiateViewController(withIdentifier: "ContactsListVC") as! ContactsListVC
        
        
        //create tabbar
        let tabbarController = AppTabsController (viewControllers: [treeVC,listVC])
        
        
        
        //push
        self.navigationController?.pushViewController(tabbarController, animated: true)
 
        
    }

```

**Comment by daniel-jonathan** [comment]
Thank you! I will publish some text for you tomorrow on this subject, if not tonight. My day job has been really busy, so apologies for the delay.

**Comment by ijameelkhan** [comment]
Any update here ?  I download this sample https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/CardTableView and it wont compile even after pod install runs sucessfully. 

<img width="702" alt="screen shot 2017-10-20 at 5 16 58 pm" src="https://user-images.githubusercontent.com/1882875/31820385-876be69a-b5ba-11e7-8b0d-558cea782a38.png">

**Comment by daniel-jonathan** [comment]
I am working on the lesson, and now investigating the CardTableView sample project. I will have more information for you later today.

**Comment by ijameelkhan** [comment]
Just an update. I have managed to achieve mostly what I wanted and here how it looks. 

![simulator screen shot 23-oct-2017 5 53 04 pm](https://user-images.githubusercontent.com/1882875/31889981-09b63b84-b81b-11e7-8a32-9e8b97db11e5.png)

Here is the code

```swift
//storyboard
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        
        //create contacts tree VC
        let treeVC = storyboard.instantiateViewController(withIdentifier: "ContactsTreeVC") as! ContactsTreeVC
        
        
        //create contacts tree VC
        let listVC = storyboard.instantiateViewController(withIdentifier: "ContactsListVC") as! ContactsListVC
        
        
        //create tabbar
        let tabbarController = AppTabsController (viewControllers: [treeVC,listVC])
        
        
        //add toolvbar
        let toolbarController = AppToolbarController(rootViewController: tabbarController)
    
        
        //wrap inside FAB Controller so we can get access .fabMenu property down the tree
        let fabController = AppFABMenuController(rootViewController: toolbarController)
        
        
        //wrap inside SnackbarController so we can get access .snackbar property down the tree
        let snackBarController = AppSnackbarController(rootViewController: fabController)
        
        
        
        //make it root
        UIView.transition(with: self.view.window!, duration: 0.5, options: UIViewAnimationOptions.transitionCrossDissolve, animations: {
   
            self.view.window?.rootViewController = snackBarController
            
        }, completion: nil)
        
        

```

Now the issue when I press on the FAB menu , my screen goes faded but menu wont show up  something like this.

![simulator screen shot 23-oct-2017 5 54 38 pm](https://user-images.githubusercontent.com/1882875/31890040-41dcf5f2-b81b-11e7-86ab-52678cf5a2b8.png)



Both ListVC and TreeVC creates its own FAB Menu because I want to show different menu with different actions in each ViewController and don't want to implement my selectors in the AppFABMenuController. 



```swift

fileprivate func layoutFABMenu(){
        
        
        //controller
        let fabController = fabMenuController as! AppFABMenuController
        
        
        //get acess to Fab menu view
        guard let fabMenu = fabMenuController?.fabMenu else{
            
            return;
        }
    
        view.layout(fabMenu)
            .size(fabController.fabMenuSize)
            .bottom(fabController.bottomInset)
            .right(fabController.rightInset)
    
    }
    

```


It would really help if you can write a detail conceptual tutorial how these controllers are made and how to combine them in different uses case.

**Comment by daniel-jonathan** [comment]
Looks good :) I am a bit swamped with work, sorry, I didn't anticipate such a busy schedule.

**Comment by ijameelkhan** [comment]
Any quick ideas for the issue at hand ?

**Comment by daniel-jonathan** [comment]
I would need to see the project and take a look. Can you send it over?

**Comment by ijameelkhan** [comment]
Download from here: https://github.com/ijameelkhan/mlmjungle_ios.git you have the access.

**Comment by daniel-jonathan** [comment]
Thanks, I have a few items to take care immediately, then I will look at this. Once again, I didn't anticipate the workload I have, so I am sorry for any delays.

**Comment by ijameelkhan** [comment]
After some testing I reached to conclusion that.

```swift 
        let blur = UIVisualEffectView(effect: UIBlurEffect(style: fabMenuBackingBlurEffectStyle))
        blurView = UIView()
        blurView?.layout(blur).edges()
        view.layout(blurView!).edges()
        view.bringSubview(toFront: fabMenu)
```

"view" variable is NOT the superview of "fabMenu" so this line has no effect

```swift
view.bringSubview(toFront: fabMenu)
```

why it happens is a mystery to me.

**Comment by daniel-jonathan** [comment]
I am looking through your sample.

**Comment by ijameelkhan** [comment]
any luck?

**Comment by daniel-jonathan** [comment]
@ijameelkhan I am working out what the issue is, because I am only seeing it in your project. Currently, I am investigating.

**Comment by daniel-jonathan** [comment]
Okay, I see the issue. You are laying out your buttons as part of the tab view controllers and not part of the `AppFABMenuController`. This means that your buttons actually exist in the sub tree of that controller. You need to move them to the `AppFABMenuController`. If you have any further issues, please reopen this and please take a look at the [CardTableView](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/CardTableView) sample.

**Comment by ijameelkhan** [comment]
Ok but then how can I achieve different menu inside TreeTab VS ListTab ? also I don't want my selectors to be inside AppFABMenuController and instead inside my actual controller.  i.e. Separation of Concerns.

**Comment by daniel-jonathan** [comment]
Just change the buttons in the AppFABMenuController, by accessing the `fabMenuController` optional property in any view controller. But add them to the correct view hierarchy position, which is the `AppFABMenuController`.

**Comment by ijameelkhan** [comment]
Ok will try and let you know. Thank you for looking into it.

**Comment by daniel-jonathan** [comment]
No worries :) I hope it works out.

**Comment by ijameelkhan** [comment]
Ok this worked as expected. Here is the latest code how I put together the entire stack.

```swift
//storyboard
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        
        //create contacts tree VC
        let treeVC = storyboard.instantiateViewController(withIdentifier: "ContactsTreeVC") as! ContactsTreeVC
        
        
        //create contacts tree VC
        let listVC = storyboard.instantiateViewController(withIdentifier: "ContactsListVC") as! ContactsListVC
        
        
        //create tabbar
        let tabbarController = AppTabsController (viewControllers: [treeVC,listVC])
        
        
        //add toolvbar
        let toolbarController = AppToolbarController(rootViewController: tabbarController)
    
        
        //wrap inside FAB Controller so we can get access .fabMenu property down the tree
        let fabController = AppFABMenuController(rootViewController: toolbarController)
        
        
        //wrap inside SnackbarController so we can get access .snackbar property down the tree
        let snackBarController = AppSnackbarController(rootViewController: fabController)
        
        
        //left vs
        let leftNavVC = storyboard.instantiateViewController(withIdentifier: "LeftNavVC") as! LeftNavVC
        
        
        //wrap inside drawer
        let navDrawerVC = AppNavigationDrawerController(rootViewController: snackBarController, leftViewController: leftNavVC, rightViewController: nil)
        
        
        //make it root
        UIView.transition(with: self.view.window!, duration: 0.5, options: UIViewAnimationOptions.transitionCrossDissolve, animations: {
   
            self.view.window?.rootViewController = navDrawerVC
            
        }, completion: nil)
        
```

Add an extension to show Toast as Part UIViewController.

```swift
func showToast(message:String) ->Void {
        
        guard let sc = snackbarController else {
            return
        }
        
        
        guard let snackbar = snackbarController?.snackbar else {
            return
        }
        
    
        
        snackbar.text = message
        sc.animate(snackbar: .visible, delay: 0.5)
        sc.animate(snackbar: .hidden, delay: 3)
        
        
        
    }
```

but the property snackbar returns after I added NavDrawer ? if I remove it all works fine. any idea ?

**Comment by daniel-jonathan** [comment]
"property snackbar returns after I added NavDrawer", is because the Snackbar is not part of the view hierarchy until the NavigationDrawer has been added. When are you calling the `showToast` method?

**Comment by ijameelkhan** [comment]
I was calling my method in viewDidLoad , so if delay it by 2 seconds it works which means you are correct. Thank you 👍

**Comment by daniel-jonathan** [comment]
You can also call it in `viewWillAppear` or `viewDidAppear` and probably not need the delay :) All the best!

**Comment by ijameelkhan** [comment]
Yes Of course thank you!
