### ISSUE TITLE
How to use TabBar, add viewcontroller container 

### ISSUE THREAD

**Issue by ismaPM** [CosmicMind/Samples#73]

**Comment by daniel-jonathan** [comment]
Have you taken a look at the [TabBar](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TabBar) and [TabsController](https://github.com/CosmicMind/Samples/tree/master/Projects/Programmatic/TabsController) sample projects? If these don't help, please reopen the issue. Thank you!
