### ISSUE TITLE
Warnings and 15 Issues in building the samples

### ISSUE THREAD

**Issue by quanguyen** [CosmicMind/Samples#74]
Hi,

I'm eager to try this great project's samples in Swift 4!

After downloading and running `./install_all_pods.sh`, every `.xcworkspace` sample that I opened, I have the same warnings and errors as in the screenshot below:

<img width="1342" alt="screen shot 2017-10-20 at 10 11 25 am" src="https://user-images.githubusercontent.com/11938078/31803837-2aab0722-b580-11e7-8297-8ab4d83ab1ee.png">

1. Why do I have `Conversion to Swift 4 is available` at the upper red border? I though the project had been converted to Swift 4, so I am not supposed to get this warning?

2. How do I fix the 15 issues at the lower red border?

Please be patient with me since I may not be familiar enough with `Material`.

Regards,

**Comment by daniel-jonathan** [comment]
No worries :) 

I believe you need to set the `Pods` project to use `Swift 4`. So open up the build settings tab in the Pods projects and search for `swift version` and set it to 4.

**Comment by quanguyen** [comment]
Yes, it just works!!

Allow me to post a screenshot for anyone who might need for reference.

<img width="1140" alt="screen shot 2017-10-20 at 10 35 46 am" src="https://user-images.githubusercontent.com/11938078/31804317-a9709174-b582-11e7-93b1-1e40182fb80d.png">

Thanks a lot, Daniel

**Comment by daniel-jonathan** [comment]
Nice, I labeled it `great first issue`, which will make it a better search result for people looking into this repo :) I will close the issue for now. Thank you!
