### ISSUE TITLE
Unable to update title and detail labels of navigationItem

### ISSUE THREAD

**Issue by quanguyen** [CosmicMind/Samples#75]
Hi,

From the sample `NavigationController` (`Programmatic`), I add my button on which when pressed, it sends a notification to update the title and detail labels of `navigationItem`.

It's strange that I cannot!

My code is just like this:

<img width="1133" alt="screen shot 2017-10-20 at 6 18 09 pm" src="https://user-images.githubusercontent.com/11938078/31818635-2abfda06-b5c3-11e7-926c-6a5e7b0f0d55.png">

(More details in my zip file)

[NavigationController.zip](https://github.com/CosmicMind/Samples/files/1401731/NavigationController.zip)

Could you show me how I should solve this?

Regards,

**Comment by quanguyen** [comment]
Hi, 

Have you got any updates on this strange issues?

Regards,

**Comment by daniel-jonathan** [comment]
Hey! To avoid any conflict issues, I needed to move `title` and `detail` to `titleLabel.text` and `detailLabel.text`. So you should update it like so: 

```swift
navigationItem.titleLabel.text = "My App Name"
navigationItem.detailLabel.text = "Details of my app"
```

If you need any further assitance, please reopen this issue. Thank you!
