### ISSUE TITLE
Swift compiler Error

### ISSUE THREAD

**Issue by guoyingtao** [CosmicMind/Samples#77]
I ran install_all_pods.sh and tried to compile Animation Example. Then I met "Swift compiler Error" as Follows:

<img width="1396" alt="2" src="https://user-images.githubusercontent.com/26723384/32059769-20451466-ba3b-11e7-9d41-11607d86b9bc.png">

**Comment by guoyingtao** [comment]
I set "Swift Language Version" to "4.0" for all target and it works now.

**Comment by daniel-jonathan** [comment]
Yes, that is the correct setting. All the best!
