### ISSUE TITLE
TabsController - iPhoneX

### ISSUE THREAD

**Issue by MattKiazyk** [CosmicMind/Samples#78]
Currently the `TabsController` example doesn't handle the iPhoneX safeAreaLayout changes.

<img width="398" alt="screenshot 2017-10-26 15 08 54" src="https://user-images.githubusercontent.com/1119565/32074654-b77cec68-ba5f-11e7-86f2-22c97305d5bc.png">

In iPhoneX scenario, the tab bar should be in the safe area, with the height stretched into the unsafe area.

The `BottomNavigationController` example is a good one that when using `UITabBar` it resizes properly.

<img width="408" alt="screenshot 2017-10-26 15 13 20" src="https://user-images.githubusercontent.com/1119565/32074843-49294508-ba60-11e7-9396-04187d7c3073.png">

Thanks!

**Comment by daniel-jonathan** [comment]
A great, thank you! I will add this fix.

**Comment by daniel-jonathan** [comment]
You can find a fix for this in [Material 2.12.10](https://github.com/CosmicMind/Material/releases/tag/2.12.10). Thank you!
