### ISSUE TITLE
        Use of unresolved identifier 'Motion' In AppMenuController (menu.views.first?.animate(animation: Motion.rotate(angle: 45)))

### ISSUE THREAD

**Issue by namuthan** [CosmicMind/Samples#9]

**Comment by daniel-jonathan** [comment]
Have you updated to the latest Material ?

**Comment by namuthan** [comment]
This is what cocopods say when I do pod install for   pod 'Material'
Installing Material (2.2.5).
I am still getting the error "Use of unresolved identifier Motion" .

**Comment by daniel-jonathan** [comment]
Material is now at 2.3.1, so possibly clear your cache. Also, pull the latest Master samples.

**Comment by namuthan** [comment]
Thanks. It worked when I updated the version to  2.3.1. I have another quick question, Is there a way to increase the width and height of the menu buttons with out them being overlapping?

**Comment by daniel-jonathan** [comment]
Awesome! Yes, when you change the size, you will also want to change the space between them. You can do that using these two properties, one being a preset and the other being a raw value. 

``` swift
/// A preset wrapper around interimSpace.
    open var interimSpacePreset = InterimSpacePreset.none {
        didSet {
            interimSpace = InterimSpacePresetToValue(preset: interimSpacePreset)
        }
    }

    /// The space between views.
    open var interimSpace: InterimSpace = 0 {
        didSet {
            layoutSubviews()
        }
    }
```

example:

``` swift
menu.interimSpacePreset = .interimSpace10

// or

menu.interimSpace = 56
```

I am closing this issue, and if you need, please reopen or create a new one.
