### ISSUE TITLE
Photos Sample not behaving like the readme gif

### ISSUE THREAD

**Issue by luongthomas** [CosmicMind/Samples#95]
I'm running on iPhone7 iOS 11 beta2 and when I run the photos sample code, (simulator or device), there are two undesired behaviors that I see.

1. pressing any photo will display the first photo (the top left photo) 

2.  Pressing an icon on the nav bar will make the icon blank.  pressing all five icons will result in an empty nav bar at the bottom.

**Comment by daniel-jonathan** [comment]
I will try this on the latest release of iOS 11, not beta, I don't support beta software. I will get back to you tomorrow :) Thank you!

**Comment by daniel-jonathan** [comment]
@luongthomas Yes, there is an issue. I will take a look and see what is happening. Thank you for sharing.

**Comment by daniel-jonathan** [comment]
The tabs are fixed, now working on the photo correctly being selected.

**Comment by daniel-jonathan** [comment]
Please update to [Material 2.12.14](https://github.com/CosmicMind/Material/releases/tag/2.12.14) and download the latest Samples repo. Thank you!
