### ISSUE TITLE
General difficulty with samples..

### ISSUE THREAD

**Issue by wdcurry** [CosmicMind/Samples#97]
hey, i am not 100% sure why, perhaps the latest bits are not updated, pod variances etc, but just about every sample, i need to convert to latest Swift, then manually correct numerous errors (focused around NSAttributedStringKey) .. and many samples just don't feel right.

Latest is the SearchBar. Upgraded, corrected three manual errors as above, ran the project, and not data rows are shown at all, with no error messages anywhere.

I realize my comments are generic, but wondering if there is a basic issue at hand that i am missing (like, can i even use xcode9.x for example?)  Thx..

**Comment by wdcurry** [comment]
.. and in walking the code, i honestly don't see where any data is even present. I must be missing something very basic.

**Comment by wdcurry** [comment]
I realized i should perhaps be using the Search Sample, but here is some general feedback: ABSOLUTE kudos for the efforts with the library, it is potentially amazing. I remember peeking at it a while back and was impressed.

BUT.. the current state of things makes it very very challenging to consider. The key to GitHub and such libraries is ease of entry, ability to quickly check samples, and a useable sample that manages at least the basic use case.

At present, it takes 5-10 minutes just getting a sample to run (and sometimes just won'). and then finding out how integrate into a working solution can be challenging. 

At a minimum, if the current samples would fire up and work, or have a quick task list of what is needed to make them work. 

I offer this not as a mindless criticism but as recognition of how much work has already gone into the library, offered to help increase its' acceptance.

**Comment by daniel-jonathan** [comment]
Hey, thank you for the feedback. Before 2018 hits, there will be many updates all focused on educating individuals on how to use and setup the library. If there is any one sample you are stuck on, let me know, but you have not mentioned how you are trying to setup the samples, is it CocoaPods, Carthage, or GitHub & workspaces? Please reopen the issue when you are ready to further pursue the samples. Thank you!

**Comment by wdcurry** [comment]
Excellent Daniel! If i get a better handle on integration the various components into my apps, i will drop more thoughts and feedback. I updated my Xcode and retested the project and now the Search Sample seems to functioning better. I *thought* i was up-to-date but apparently not! My bad. 

My current struggle is the merging of storyboard and progammically-based code as there are times things just seem so damn challenging to get instantiated.

**Comment by daniel-jonathan** [comment]
In Material 3, which is being worked on, there is a much greater effort to add storyboard support. I am not personally a storyboard programmer, so it wasn't the main priority.

**Comment by wdcurry** [comment]
Excellent.. there is one general thought i have which likely will be too much work, but.. the structure of the samples deters the merging of disparate examples. Each seems to be formed with root settings. I would gently suggest to create a generic, bland and open sample architectural scenario, which makes it much easier to drop samples into each other. Case in point is merging the Search sample with the navigationController samples. One needs to truly dig deep just to get to the heart of how to use the Search as it is, and to integrate it to outside usage.. well, honestly, it is just easier to use the generic search controller, despite missing out on the extra features. 

The key to getting a wider-scoped library to elevate to the next level is ease of adoption: Job1 ;)

thanks for listening.

**Comment by daniel-jonathan** [comment]
No disagreement there. I am making an entire documentation centre with robust samples and much more. It will be subscription based as maintaining this project has become a full time job. There will be much more than just samples, but that is where things are going.
