### ISSUE TITLE
How to change Drawer width programatically

### ISSUE THREAD

**Issue by SandeepCBL** [CosmicMind/Samples#98]
I want to set drawer width to 80% of screen width. Is there any way in NavigationDrawerController.

**Comment by daniel-jonathan** [comment]
Try the function below:

```swift
open func setLeftViewWidth(width: CGFloat, isHidden: Bool, animated: Bool, duration: TimeInterval = 0.5) {
```
If you need further help, please reopen this issue :) Thank you!
