### ISSUE TITLE
I met "compile error" when I built samples

### ISSUE THREAD

**Issue by guoyingtao** [CosmicMind/Samples#99]
I found the samples were still for swift 3.
Is it convenient for you to update them for swift 4? Thank you!

**Comment by daniel-jonathan** [comment]
Yes, and if you know which ones you had trouble with, please add them to this issue :)

**Comment by guoyingtao** [comment]
Like Transitions and TransitionsWithIdentifier

**Comment by daniel-jonathan** [comment]
I updated those two projects. If you find anymore, please let me know :) Thank you!

**Comment by wdcurry** [comment]
CollectionView has 15+ errors on compile.

**Comment by daniel-jonathan** [comment]
@wdcurry sorry for the delay, let me take a look.

**Comment by wdcurry** [comment]
No worries, i know this is all volunteer efforts, and your library is massive, thanks!

**Comment by daniel-jonathan** [comment]
@wdcurry You will want to use this commit: 2aa73721d12e0ffea5bce98432a3d6aefdea5e5f for Material, and pull the latest[Samples](https://github.com/CosmicMind/Samples) repo. 

Let me know if there are any further issues :)

**Comment by wdcurry** [comment]
Thanks! a quick refresher: download zip, "pod install" in root, build ok. Should we need to do anything more? I ask as i am getting a runtime error on startup:
"Could not cast value of type 'UICollectionViewFlowLayout' (0x10a613ca0) to 'Material.CollectionViewLayout' (0x10773d798).
2017-12-04 12:37:34.770224-0400 CollectionView[14265:1642531] Could not cast value of type 'UICollectionViewFlowLayout' (0x10a613ca0) to 'Material.CollectionViewLayout' (0x10773d798)."

I have not converted to Swift4 as i had to do in prior samples.

Thanks, and hopefully this question helps others.

**Comment by daniel-jonathan** [comment]
@wdcurry when you do a `pod install` you are installing the `master` branch. I put the fix on a commit and once I go through the issues today, I will make a release, which will allow you to use the `master` branch as you are.

**Comment by wdcurry** [comment]
oh crap, sorry, brainfart here ;) I will leave that comment here for comedic relief ;)

**Comment by daniel-jonathan** [comment]
lol :)
